DragaliaAPI.Test/Unit/Services/ApiRepositoryTest.cs, DragaliaAPI/Models/Data/ManaNodes.cs, DragaliaAPI/Models/Database/Savefile/DbPlayerCharaData.cs, DragaliaAPI/Models/Dragalia/MessagePackFormatters/BoolToIntFormatter.cs, DragaliaAPI/Models/Dragalia/Responses/UpdateData/Chara.cs, DragaliaAPI/Services/ApiRepository.cs
Adjustments to conversion from and to a ManaNode Flag
Changed DbCharFactory to accept actual AdventurerData instead of an id (mostly for rarity related reasons)
=> Adjustment to ManaNodes flag conversion and Charas

DragaliaAPI.Database.Test/DragaliaAPI.Database.Test.csproj, DragaliaAPI.Database.Test/Repositories/UnitRepositoryTest.cs, DragaliaAPI.Database/DragaliaAPI.Database.csproj, DragaliaAPI.Shared.Test/DragaliaAPI.Shared.Test.csproj, DragaliaAPI.Shared/DragaliaAPI.Shared.csproj, DragaliaAPI.Test/DragaliaAPI.Test.csproj, DragaliaAPI.Test/Integration/CustomWebApplicationFactory.cs, DragaliaAPI.Test/Integration/IntegrationTestFixture.cs, DragaliaAPI.Test/Unit/Services/DeviceAccountServiceTest.cs, DragaliaAPI/Controllers/Dragalia/RedoableSummonController.cs, DragaliaAPI/Dockerfile, DragaliaAPI/DragaliaAPI.csproj, DragaliaAPI/Models/Generated/Components.cs, DragaliaAPI/Program.cs, DragaliaAPI/Services/DeviceAccountService.cs, DragaliaAPI/Services/SessionService.cs, DragaliaAPI/Services/SummonService.cs, DragaliaAPI/appsettings.json
Some minor code changes based on new warnings and slight changes -- most notably the hashing algorithm for passwords has changed
=> Upgrade to .NET 7

.github/workflows/build.yml, .github/workflows/lint.yml, .github/workflows/test.yml
Forgot this in the main upgrade commit
=> Upgrade workflows to .NET 7

DragaliaAPI.Database/ApiContext.cs, DragaliaAPI.Database/ConfigureDatabase.cs, DragaliaAPI.Database/Entities/DbPlayerCharaData.cs, DragaliaAPI.Database/Entities/DbSetUnit.cs, DragaliaAPI.Database/Repositories/IInventoryRepository.cs, DragaliaAPI.Database/Repositories/IUnitRepository.cs, DragaliaAPI.Database/Repositories/InventoryRepository.cs, DragaliaAPI.Database/Repositories/UnitRepository.cs, DragaliaAPI.Database/Utils/CharaConstants.cs, DragaliaAPI.Shared/Definitions/DataAdventurer.cs, DragaliaAPI.Shared/Definitions/Enums/ManaNodes.cs, DragaliaAPI.Shared/Definitions/Enums/Materials.cs, DragaliaAPI.Shared/Definitions/Enums/UnitDataEnums.cs, DragaliaAPI.Shared/DragaliaAPI.Shared.csproj, DragaliaAPI.Shared/Resources/adventurers.json, DragaliaAPI.Shared/Resources/mananodes.json, DragaliaAPI.Shared/Services/CharaDataService.cs, DragaliaAPI.Test/Integration/Dragalia/CharaTest.cs, DragaliaAPI.Test/Integration/IntegrationTestFixture.cs, DragaliaAPI/Controllers/Dragalia/CharaController.cs, DragaliaAPI/Controllers/Dragalia/PresentController.cs, DragaliaAPI/Models/Generated/Components.cs
Proper mana node unlocks (Missing material cost calculation/deduction)
Chara Sets
=> More Chara Controller

DragaliaAPI.Database/Repositories/IPartyRepository.cs, DragaliaAPI.Database/Repositories/PartyRepository.cs, DragaliaAPI.Test/Integration/Dragalia/DungeonTest.cs, DragaliaAPI.Test/Integration/Dragalia/PartyTest.cs, DragaliaAPI.Test/Integration/IntegrationTestFixture.cs, DragaliaAPI.Test/Unit/Controllers/DungeonControllerTest.cs, DragaliaAPI.Test/Unit/Controllers/PartyControllerTest.cs, DragaliaAPI/Controllers/Dragalia/DungeonController.cs, DragaliaAPI/Controllers/Dragalia/PartyController.cs, DragaliaAPI/Models/Generated/Components.cs
These miscallaneous endpoints were missed off before but were not too hard to implement. Closes #37
=> Add /quest/fail and /party/update_party_name

DragaliaAPI.Test/Integration/Dragalia/ToolTest.cs, DragaliaAPI.Test/Unit/Services/DungeonServiceTest.cs, DragaliaAPI/Controllers/Dragalia/ToolController.cs, DragaliaAPI/Controllers/Dragalia/WebviewVersionController.cs, DragaliaAPI/Controllers/DragaliaControllerBase.cs, DragaliaAPI/Controllers/DragliaControllerAttribute.cs, DragaliaAPI/DragaliaAPI.csproj, DragaliaAPI/Middleware/SessionLookupMiddleware.cs, DragaliaAPI/Pages/News.cshtml, DragaliaAPI/Pages/News.cshtml.css, DragaliaAPI/Pages/NewsModel.cs, DragaliaAPI/Resources/news.json
Adds a basic welcome page to the server.
Also, completely randomly, adds `tool/reauth`, because I suddenly saw it being called during testing
=> Add info page

DragaliaAPI.Test/Integration/Other/DragalipatchTest.cs, DragaliaAPI.Test/Unit/Controllers/DragalipatchControllerTest.cs, DragaliaAPI/Controllers/Other/DragalipatchController.cs, DragaliaAPI/Models/DragalipatchConfig.cs, DragaliaAPI/Program.cs, DragaliaAPI/appsettings.Testing.json, DragaliaAPI/appsettings.json
Adds an endpoint for interfacing with and sending configuration options to Dragalipatch.
=> Add Dragalipatch endpoint

DragaliaAPI.Test/Integration/Dragalia/UserTest.cs, DragaliaAPI/Controllers/Dragalia/UserController.cs, DragaliaAPI/Pages/News.cshtml, DragaliaAPI/Resources/news.json
- Update homepage
- Add /user/get_n_account_info in an attempt to allow account linking in-game -- some users are reporting not seeing the popup on login.
=> Further BaaS tweaks

DragaliaAPI.Database/Entities/DbPlayerCharaData.cs, DragaliaAPI.Shared.Test/Unit/MasterAssetTest.cs, DragaliaAPI.Shared/MasterAsset/Models/CharaData.cs, DragaliaAPI.Shared/Resources/CharaData.json, DragaliaAPI.Test/Integration/Dragalia/CharaTest.cs, DragaliaAPI/Controllers/Dragalia/CharaController.cs
=> Fixed omnicite upgrading

DragaliaAPI/Controllers/DragaliaControllerBase.cs, DragaliaAPI/Middleware/AccountIdEnricherMiddleware.cs, DragaliaAPI/Program.cs, DragaliaAPI/Services/AuthService.cs, DragaliaAPI/appsettings.json
- Add middleware to inject DeviceAccountId into all logs during a request's lifetime (controllers, DB errors, etc) instead of just the request logging at the end
- Fix a typo causing save import errors to not log the cause
=> Improve logging

DragaliaAPI.Database/Repositories/QuestRepository.cs, DragaliaAPI.Database/Repositories/UnitRepository.cs, DragaliaAPI/Controllers/Dragalia/CharaController.cs, DragaliaAPI/Controllers/Dragalia/QuestController.cs, DragaliaAPI/Middleware/ExceptionHandlerMiddleware.cs
Also:
- Fix some queries that were incorrectly filtered
- Add MessagePackSerializationException alongside TaskCancelledException to endpoints that return 5xx to make the client retry
=> M O R E L O G G I N G

DragaliaAPI/Controllers/Dragalia/CharaController.cs, DragaliaAPI/Pages/News.cshtml, DragaliaAPI/Pages/NewsModel.cs, DragaliaAPI/Resources/news.json, DragaliaAPI/Resources/news.schema.json, DragaliaAPI/Services/AuthService.cs
- Update news page with some new text
- Update news page to support max. 5 headlines and with new headline about mana circles bug
-  TODO: make this part of the helm chart so no merge requests required
- Downgrade token errors and invalid json in savefile errors to warnings because they aren't necessarily my fault
=> News updates

DragaliaAPI.Database/DatabaseConfiguration.cs, docker-compose.yml
Corrections to compose file, should fix issues setting up the postgresql container
=> Docker compose changes

DragaliaAPI.Database.Test/Repositories/UnitRepositoryTest.cs, DragaliaAPI.Database/ApiContext.cs, DragaliaAPI.Database/Entities/DbPlayer.cs, DragaliaAPI.Database/Entities/DbWeaponSkin.cs, DragaliaAPI.Database/Entities/Scaffold/DbDetailedPartyUnit.cs, DragaliaAPI.Database/Migrations/20230127232342_1-1-0-alpha_5.Designer.cs, DragaliaAPI.Database/Migrations/20230127232342_1-1-0-alpha_5.cs, DragaliaAPI.Database/Repositories/UnitRepository.cs, DragaliaAPI.Test/Integration/Other/SavefileImportTest.cs, DragaliaAPI/Controllers/Dragalia/DungeonRecordController.cs, DragaliaAPI/Controllers/Dragalia/LoadController.cs, DragaliaAPI/Models/AutoMapper/UnitMapProfile.cs, DragaliaAPI/Models/AutoMapper/UnitReverseMapProfile.cs, DragaliaAPI/Models/Generated/Components.cs, DragaliaAPI/Services/SavefileService.cs
- Adds PlayerWeaponSkins table
- Adds these to save import
- Resets all save import times so people get their weapon skins
=> Add weapon skins

DragaliaAPI.Database.Test/DragaliaAPI.Database.Test.csproj, DragaliaAPI.Database/DragaliaAPI.Database.csproj, DragaliaAPI.Shared.Test/DragaliaAPI.Shared.Test.csproj, DragaliaAPI.Test/DragaliaAPI.Test.csproj, DragaliaAPI/DragaliaAPI.csproj, DragaliaAPI/Resources/news.json, DragaliaAPI/appsettings.Development.json, DragaliaAPI/appsettings.json
Also update the news page with info of #121
=> Change logging to async

DragaliaAPI.Test/Integration/Other/SavefileImportTest.cs, DragaliaAPI/Controllers/Other/PingController.cs, DragaliaAPI/Middleware/PodNameEnricher.cs, DragaliaAPI/Pages/News.cshtml, DragaliaAPI/Program.cs, DragaliaAPI/appsettings.Development.json
- Adds ping controller for liveness checks (over using /health, which will cause the pods to restart if the DB can't be reached -- doesn't really make sense)
- Adds log enricher for HOSTNAME env var to be able to filter logs per pod if autoscaling
=> K8s improvements

DragaliaAPI/Controllers/Dragalia/LoadController.cs, DragaliaAPI/Controllers/Dragalia/MissionController.cs, DragaliaAPI/Controllers/Dragalia/MypageController.cs, DragaliaAPI/Models/Generated/Components.cs, DragaliaAPI/Models/Generated/Responses.cs
=> Stop using static data for /mypage/info

DragaliaAPI.Database/Entities/DbPlayer.cs, DragaliaAPI.Database/Entities/Scaffold/DbDetailedPartyUnit.cs, DragaliaAPI.Database/Repositories/IWeaponRepository.cs, DragaliaAPI.Database/Repositories/WeaponRepository.cs, DragaliaAPI.Test/Integration/Other/SavefileImportTest.cs, DragaliaAPI.Test/Unit/Controllers/DungeonStartControllerTest.cs, DragaliaAPI/AutoMapper/Profiles/UnitMapProfile.cs, DragaliaAPI/AutoMapper/Profiles/UnitReverseMapProfile.cs, DragaliaAPI/Controllers/Dragalia/DungeonStartController.cs, DragaliaAPI/Controllers/Dragalia/LoadController.cs, DragaliaAPI/Services/SavefileService.cs
- Fix weapon passive abilities not being in quests
- Add weapon passive abilities to save import, and delete them upon importing a save
=> Fix to weapon passive abilities

.gitignore, DragaliaAPI.Photon.Plugin/DragaliaAPI.Photon.Plugin.csproj, DragaliaAPI.Photon.Plugin/GluonPlugin.cs, DragaliaAPI.Photon.Plugin/GluonPluginFactory.cs, DragaliaAPI.Photon.Plugin/Properties/AssemblyInfo.cs, DragaliaAPI.sln, DragaliaAPI/Controllers/Dragalia/LoadController.cs, DragaliaAPI/Controllers/Dragalia/MatchingController.cs
- Adds the photon plugin to the monorepo
- This can be debugged locally, it expects a PhotonServer/ folder in the solution directory
- Sends `photon.dawnshard.co.uk` as the multi server host from `/load/index` to point at a test instance of photon
=> Photon test

.github/workflows/deploy.yaml, .github/workflows/publish-push.yaml, .github/workflows/publish.yaml
Adjust publish workflow to fix errors
=> Fix workflows

DragaliaAPI.Photon.Shared/Models/GameBase.cs, DragaliaAPI.Photon.Shared/Models/HeroParam.cs, DragaliaAPI.Photon.Shared/Models/IGame.cs, DragaliaAPI.Photon.StateManager/Controllers/PingController.cs, DragaliaAPI.Photon.StateManager/Models/RedisGame.cs, DragaliaAPI.Photon.StateManager/Program.cs, DragaliaAPI.Photon.StateManager/RedisHealthCheck.cs
Also add some xml docs that were missing (but not all of them, too lazy)
=> Add healthchecks to state manager

DragaliaAPI/Controllers/Dragalia/LoadController.cs, DragaliaAPI/Services/Photon/MatchingService.cs, DragaliaAPI/appsettings.json
- Make photon server url driven through config
- Add extra logging to MatchingService
=> Add photon configuration

DragaliaAPI.Database.Test/Repositories/FortRepositoryTest.cs, DragaliaAPI.Database/Repositories/FortRepository.cs
- Check whether fort data exists before initializing it
=> Fix primary key errors in InitializeFort

DragaliaAPI/Features/Stamp/StampController.cs, DragaliaAPI/Services/Game/LoadService.cs
Try sorting stamp lists (as they are in official responses) in response to reports of disappearing stamps
=> Order stamp lists

DragaliaAPI/Services/Game/SavefileService.cs
Also delete it on removing a save
=> Add shop info initialization

DragaliaAPI/Features/Present/Present.cs
Forgot that this field is nullable
=> Fix January 1 1970 presents

DragaliaAPI.Database/Repositories/UnitRepository.cs, DragaliaAPI.Integration.Test/Features/Fort/FortTest.cs
=> Make UnitRepository use EditSkillLevelNum for shared skills (fix gala zethia skill issue)

DragaliaAPI.Photon.StateManager/Program.cs
Index isn't being created when Ceris is using it for some reason
=> Add index logging

DragaliaAPI/Features/SavefileUpdate/V7Update.cs, DragaliaAPI/Features/Shop/PaymentService.cs, DragaliaAPI/Services/Game/StoryService.cs
Sorry Luke but I can't install VS preview
=> Remove primary constructors

.github/workflows/deploy.yaml, .github/workflows/publish-push.yaml
Deploy the state manager and API server into different GitHub environments, and have them inherit the kubernetes variables from there.
=> Update CI deployment environments

DragaliaAPI.Test/Services/BonusServiceTest.cs, DragaliaAPI/Features/Dungeon/DungeonStartService.cs, DragaliaAPI/Models/Generated/Components.cs, DragaliaAPI/Pages/News.cshtml, DragaliaAPI/Services/Game/BonusService.cs, DragaliaAPI/Services/IBonusService.cs
Perform facility bonus lookup in /dungeon_start/start
=> Fix facility bonus

DragaliaAPI.Integration.Test/Features/Dmode/DmodeTest.cs, DragaliaAPI/Features/Dmode/DmodeRepository.cs, DragaliaAPI/Features/Dmode/IDmodeRepository.cs, DragaliaAPI/Features/DmodeDungeon/DmodeDungeonService.cs, DragaliaAPI/Services/Game/StoryService.cs
- Fix character edit skills not being saved properly
- Fix DUMMY weapon abilities
=> Kaleidoscape fixes

DragaliaAPI.Shared/Definitions/Enums/DmodeEnemyLevelType.cs, DragaliaAPI.Shared/MasterAsset/Models/Dmode/DmodeEnemyParam.cs, DragaliaAPI.Shared/MasterAsset/Models/QuestDrops/EnemyParam.cs, DragaliaAPI.Test/Features/Dmode/DmodeServiceTest.cs, DragaliaAPI/Features/Dmode/DmodeService.cs, DragaliaAPI/Features/DmodeDungeon/DmodeDungeonService.cs
Uses some more properties from EnemyParam to correctly set levels for second forms and boss-spawned enemies
=> Fix boss enemy level issues

DragaliaAPI.Database.Test/DbTestFixture.cs, DragaliaAPI.Database.Test/Repositories/UnitRepositoryTest.cs, DragaliaAPI.Database/Repositories/StoryRepository.cs, DragaliaAPI.Integration.Test/Features/SavefileUpdate/ISavefileUpdateTest.cs, DragaliaAPI.Test/RepositoryTestFixture.cs, DragaliaAPI/Features/SavefileUpdate/V9Update.cs, DragaliaAPI/Services/Game/SavefileService.cs
=> Fix characters being given without stories

DragaliaAPI/Features/DmodeDungeon/DmodeDungeonService.cs
Not entirely sure about this logic, someone double check this
=> Make dmode max out skill and ability levels

DragaliaAPI.Database/Repositories/QuestRepository.cs, DragaliaAPI.Integration.Test/Dragalia/DungeonRecordTest.cs, DragaliaAPI.Integration.Test/Dragalia/UpdateTest.cs, DragaliaAPI/Controllers/Dragalia/UpdateController.cs
- Fix crash on /dungeon_record/record where no quest entity
- Fix null list crash on /update/reset_new
=> Fix server errors on quest completion and reset_new

DragaliaAPI/Features/Dungeon/Start/DungeonStartService.cs, DragaliaAPI/Services/Game/HelperService.cs
Also fix helpers not persisting on repeating quests
=> Add Mym helper

DragaliaAPI.Integration.Test/Features/QuestBonusTest.cs, DragaliaAPI.Shared/DragaliaAPI.Shared.csproj, DragaliaAPI.Shared/MasterAsset/MasterAsset.cs, DragaliaAPI.Shared/MasterAsset/Models/QuestDrops/QuestBonusReward.cs, DragaliaAPI.Shared/Resources/QuestDrops/QuestBonusRewards.json, DragaliaAPI/Features/Quest/QuestService.cs, DragaliaAPI/Features/Reward/Entity.cs, DragaliaAPI/Resources/news.json
=> Add rewards to quest bonuses

DragaliaAPI.Shared/Resources/Missions/MissionProgressionInfo.json, DragaliaAPI/Features/Missions/MissionInitialProgressionService.cs, DragaliaAPI/Features/Player/UserService.cs
Also adds logging to stamina usage
=> Endeavor fixes 2

DragaliaAPI.Database/Utils/CharaUtils.cs, DragaliaAPI/AutoMapper/CharaStatResolvers.cs
Additionally tidy up CharaUtils and fix warnings about integer division
=> Fix node stat calculations overflowing

DragaliaAPI/Pages/Account.razor
Forgot to serialize DateTimeOffset/TimeSpan as long/int (use ApiJsonOptions as base)
and forgot to serialize bools as 1/0
=> Fix json options

DragaliaAPI/Authentication/HttpRequestState.cs, DragaliaAPI/Pages/Account.razor, DragaliaAPI/Pages/Index.razor, DragaliaAPI/Pages/News.razor, DragaliaAPI/Pages/_Host.cshtml, DragaliaAPI/RazorComponents/Acknowledgement.razor, DragaliaAPI/RazorComponents/MainLayout.razor
- Fix some css issues causing poor scaling
- Add dark mode toggle
- Use accent colours
=> Update website styling

DragaliaAPI.Integration.Test/Features/QuestBonusTest.cs, DragaliaAPI/Features/Quest/QuestCacheService.cs, DragaliaAPI/Features/Quest/QuestService.cs
- Set ReserveCount to 0 when not claiming a bonus
- Make cache keys have infinite duration
=> Fix quest bonus popup appearing repeatedly on login

DragaliaAPI/Services/Game/LoadService.cs
Add empty album_dragon_list to preserve save editor compatibility
=> Fix save editor interaction

DragaliaAPI/Models/Generated/LoadIndexData.cs
We need to serialize this to be compatible with the save editor
=> Remove JsonIgnore from fort_bonus_list

DragaliaAPI.Shared/Resources/Missions/MissionProgressionInfo.json
Quest ID was mistakenly for hard mode
=> Fix Clear Chapter 6 3-3 royal regimen endeavour

DragaliaAPI.Photon.Plugin/DragaliaAPI.Photon.Plugin.csproj, DragaliaAPI/RazorComponents/TimeAttack/OwnClear.razor
=> Fix own clear ranking

DragaliaAPI/Program.cs, DragaliaAPI/RazorComponents/LoginButton.razor
- Suppress log lines with `JSDisconnectedException` from mudblazor internals
- Catch `TaskCancelledException` when navigating to BaaS
=> Fix blazor spam logs

DragaliaAPI.Integration.Test/Features/Dungeon/DungeonStartTest.cs, DragaliaAPI.Test/Features/Dungeon/Record/DungeonRecordServiceTest.cs, DragaliaAPI/Features/Dungeon/IDungeonStartService.cs, DragaliaAPI/Features/Dungeon/Record/DungeonRecordService.cs, DragaliaAPI/Features/Dungeon/Start/DungeonStartController.cs, DragaliaAPI/Features/Dungeon/Start/DungeonStartService.cs, DragaliaAPI/Features/Quest/IQuestService.cs, DragaliaAPI/Features/Quest/QuestService.cs
- Add validation of quest stamina on start
=> Fix quest stamina being deducted on first clears

DragaliaAPI.Integration.Test/Features/Dungeon/DungeonRecordTest.cs, DragaliaAPI.Integration.Test/Features/Dungeon/DungeonSkipTest.cs, DragaliaAPI/Features/Dungeon/Record/DungeonRecordService.cs
#439 still had the stamina check after `ProcessQuestCompletion` so the quest state would never be <3
=> Fix stamina actually

DragaliaAPI.Photon.Plugin/DragaliaAPI.Photon.Plugin.csproj, DragaliaAPI.Photon.Plugin/GluonPlugin.cs
- Check key in dict in HeroParam callback in case someone left before
response arrived
- Don't deserialize on failure response
- Don't process leave events if ActorNr = -1
=> Plugin fixes

DragaliaAPI.Integration.Test/Features/Dungeon/__snapshots__/DungeonStartTest.Start_OneTeam_HasExpectedPartyUnitList.snap, DragaliaAPI.Integration.Test/Features/Present/PresentTest.cs, DragaliaAPI.Shared/Definitions/Enums/Dragons.cs, DragaliaAPI.Shared/Definitions/Enums/Emblems.cs, DragaliaAPI.Shared/Definitions/Enums/Weapons.cs, DragaliaAPI/Controllers/Dragalia/UpdateController.cs, DragaliaAPI/Features/GraphQL/GraphQlController.cs, DragaliaAPI/Features/Reward/Handlers/EmblemRewardHandler.cs, DragaliaAPI/Features/Reward/Handlers/GenericRewardHandler.cs, DragaliaAPI/Features/Reward/Handlers/GrantReturn.cs, DragaliaAPI/Features/Reward/Handlers/IRewardHandler.cs, DragaliaAPI/Features/Reward/RewardService.cs, DragaliaAPI/ServiceConfiguration.cs, DragaliaAPI/Services/Game/SavefileService.cs
- Also features a small refactor to break grant logic into individual handlers going forward
- Set imported saves to max version
- Fix reset_new for emblems
=> Add epithets to RewardService

DragaliaAPI.Integration.Test/Features/Version/VersionTest.cs, DragaliaAPI.Integration.Test/TestFixture.cs, DragaliaAPI/Controllers/BypassResourceVersionCheckAttribute.cs, DragaliaAPI/Controllers/Dragalia/DeployController.cs, DragaliaAPI/Controllers/Dragalia/EulaController.cs, DragaliaAPI/Controllers/Dragalia/ToolController.cs, DragaliaAPI/Controllers/DragaliaControllerBase.cs, DragaliaAPI/Features/Version/IResourceVersionService.cs, DragaliaAPI/Features/Version/Platform.cs, DragaliaAPI/Features/Version/ResourceVersionService.cs, DragaliaAPI/Features/Version/VersionController.cs, DragaliaAPI/Middleware/ResourceVersionActionFilter.cs, DragaliaAPI/Models/Generated/Requests.cs, DragaliaAPI/ServiceConfiguration.cs
Adds an action filter that redirects users to the title screen if the resource version is updated  during their active session.
=> Add resource version action filter

DragaliaAPI.Database/ApiContext.cs, DragaliaAPI.Database/Entities/DbUserImpersonation.cs, DragaliaAPI.Database/Migrations/20231023184812_user-impersionation.Designer.cs, DragaliaAPI.Database/Migrations/20231023184812_user-impersionation.cs, DragaliaAPI/Features/GraphQL/ImpersionationMutations.cs, DragaliaAPI/Middleware/SessionAuthenticationHandler.cs
Allows developers to log in as another user in development mode
TODO: consider using redis key instead, lower performance impact may allow enabling it in prod
=> Add user impersonation

DragaliaAPI.Test/Features/Missions/MissionControllerTest.cs, DragaliaAPI/Controllers/Dragalia/MissionController.cs, DragaliaAPI/Features/Missions/IMissionService.cs, DragaliaAPI/Features/Missions/MissionService.cs
- Fix drill mission group rewards being infinitely claimable
- Fix "Complete an item summon" mission showing when all missions completed
=> More royal regimen fixes

DragaliaAPI/Controllers/Dragalia/WeaponBodyController.cs, DragaliaAPI/Features/Album/AlbumController.cs
This controller which does not return any actual data should prevent the game from softlocking when attempting to access Notte's Notes.
=> Add stub album implementation

.gitignore, DragaliaAPI.Integration.Test/Features/Trade/TreasureTradeTest.cs, DragaliaAPI/Features/Reward/Handlers/WeaponSkinHandler.cs, DragaliaAPI/Features/Reward/RewardService.cs
- Make RewardService throw if grant failed
=> Fix weapon skin trades

DragaliaAPI.Database/Repositories/IInventoryRepository.cs, DragaliaAPI.Database/Repositories/InventoryRepository.cs, DragaliaAPI.Integration.Test/Features/Dmode/DmodeTest.cs, DragaliaAPI.Integration.Test/Features/Login/LoginTest.cs, DragaliaAPI/Features/Reward/Handlers/DragonGiftHandler.cs
Fixes people not being able to log in after #477 added `RewardService` exception on handler not found, oops :hand_over_mouth:
=> Add dragon gift reward handler

.github/workflows/test.yaml, DragaliaAPI.Database/DatabaseConfiguration.cs, docker-compose.yml
- Add support for POSTGRES_DATABASE env var
=> Upgrade local compose file to postgres 16

DragaliaAPI.Photon.StateManager/Dockerfile, DragaliaAPI/Dockerfile
Ensure that required files for build are copied to the container
=> Fix docker builds

DragaliaAPI.Integration.Test/Features/Dungeon/DungeonStartTest.cs, DragaliaAPI/Features/Dungeon/Start/DungeonStartController.cs
Closes #515 
I've opted to use the first Chronos for the sole reason that I think the phraegenoth move is more interesting
=> Fix chronos not spawning

DragaliaAPI/Controllers/Dragalia/FriendController.cs
Prevents a few UI softlocks in this interface caused by the normal 404 error popup.
=> Add stub friend endpoints

DragaliaAPI.Database/Entities/DbPlayerDragonReliability.cs, DragaliaAPI.Database/Utils/DragonConstants.cs, DragaliaAPI.Integration.Test/Dragalia/DragonTest.cs, DragaliaAPI.Test/Services/DragonServiceTest.cs, DragaliaAPI/Features/Missions/IMissionProgressionService.cs, DragaliaAPI/Features/Missions/MissionProgressionService.cs, DragaliaAPI/Models/Generated/Components.cs, DragaliaAPI/Services/Game/DragonService.cs, DragaliaAPI/Services/Game/SummonService.cs
I thought I was fixing a bug with dragon bond missions, described by the included new test, but it turns out that this was already fixed. Instead this PR can just be for minor refactoring.
=> DragonService refactoring

DragaliaAPI.Integration.Test/Features/Dungeon/DungeonRecordTest.cs, DragaliaAPI.MissionDesigner/Missions/TollOfTheDeep.cs, DragaliaAPI.MissionDesigner/Missions/TrickOrTreasure.cs, DragaliaAPI.MissionDesigner/Models/EventMission/EventChallengeBattleClearMission.cs, DragaliaAPI.Shared/MasterAsset/Models/QuestRewards/QuestScoreMissionData.cs, DragaliaAPI.Shared/Resources/Missions/MissionProgressionInfo.json, DragaliaAPI/Features/Dungeon/QuestCompletionService.cs, DragaliaAPI/Features/Missions/IMissionProgressionService.cs, DragaliaAPI/Features/Missions/MissionProgressionService.cs, DragaliaAPI/Features/Quest/QuestService.cs
- Add Trick or Treasure compendium endeavours
- Change challenge battle clear mission to use variation type to support real events with co-op
- Fix boss battles not granting points; this was another case of indexing into the scores incorrectly
=> Add Trick or Treasure endeavours

.github/workflows/missiondesigner.yaml, DragaliaAPI.MissionDesigner/Missions/AccursedArchives.cs, DragaliaAPI.MissionDesigner/Models/Attributes/EventIdAttribute.cs, DragaliaAPI.MissionDesigner/Models/Attributes/MissionTypeAttribute.cs, DragaliaAPI.MissionDesigner/Models/EventMission/EventChallengeBattleClearMission.cs, DragaliaAPI.Shared/MasterAsset/Models/Missions/MissionCompleteType.cs, DragaliaAPI.Shared/Resources/Missions/MissionProgressionInfo.json, DragaliaAPI/Features/Missions/IMissionProgressionService.cs, DragaliaAPI/Features/Missions/MissionProgressionService.cs, DragaliaAPI/Features/Quest/QuestService.cs
- Add QuestId as Parameter4 to EventChallengeBattleClear because the Accursed Archives is a dumb event and master/expert challenge battles are both the same variationtype
=> Add The Accursed Archives endeavours

DragaliaAPI.Integration.Test/Features/Dungeon/DungeonRecordTest.cs, DragaliaAPI.Shared/MasterAsset/MasterAssetData.cs, DragaliaAPI.Shared/MasterAsset/Models/QuestData.cs, DragaliaAPI/Features/Quest/QuestService.cs
Implements a random chance on clearing a facility event boss battle to unlock the EX boss battle. Closes #591
The current mechanic is one per three clears of the quest, or a 15% chance otherwise.
=> Add EX battle unlock mechanic

DragaliaAPI.Integration.Test/Features/Event/MemoryEventTest.cs, DragaliaAPI.Integration.Test/Features/Missions/MissionTest.cs, DragaliaAPI.MissionDesigner/Missions/MiracleOfDragonyule.cs, DragaliaAPI.Shared/MasterAsset/Models/QuestData.cs, DragaliaAPI.Shared/Resources/Missions/MissionProgressionInfo.json, DragaliaAPI/Features/Missions/MissionService.cs, DragaliaAPI/Features/Reward/Handlers/GrantReturn.cs, DragaliaAPI/Features/Reward/Handlers/StampRewardHandler.cs
- Add obsolete memory event mission logic
- Add Stamp reward handler
- Make EX boss battles count towards boss battle clear missions
=> Add The Miracle of Dragonyule endeavours

DragaliaAPI.Photon.Plugin/StateManagerPlugin.cs
- Make game close requests synchronous
=> Fix StateManagerPlugin using wrong bearer token

DragaliaAPI/Pages/News/NewsWebview.razor.css
Reverts SapiensAnatis/Dawnshard#632
Makes css worse somehow
=> Revert "Update NewsWebview.razor.css"

DragaliaAPI.Integration.Test/Features/Maintenance/MaintenanceTest.cs, DragaliaAPI.Integration.Test/Features/Zena/ZenaTest.cs, DragaliaAPI.Integration.Test/TestFixture.cs, DragaliaAPI/Controllers/BypassResourceVersionCheckAttribute.cs, DragaliaAPI/Controllers/Dragalia/DeployController.cs, DragaliaAPI/Controllers/Dragalia/EulaController.cs, DragaliaAPI/Controllers/Dragalia/ToolController.cs, DragaliaAPI/Controllers/DragaliaControllerBase.cs, DragaliaAPI/Features/Maintenance/MaintenanceController.cs, DragaliaAPI/Features/Maintenance/MaintenanceService.cs, DragaliaAPI/Features/Version/VersionController.cs, DragaliaAPI/Features/Zena/GetTeamDataResponse.cs, DragaliaAPI/Features/Zena/IZenaService.cs, DragaliaAPI/Features/Zena/ZenaController.cs, DragaliaAPI/Features/Zena/ZenaService.cs, DragaliaAPI/Middleware/MaintenanceActionFilter.cs, DragaliaAPI/Middleware/NotFoundHandlerMiddleware.cs, DragaliaAPI/Middleware/ResourceVersionActionFilter.cs, DragaliaAPI/Models/Options/MaintenanceOptions.cs, DragaliaAPI/Program.cs, DragaliaAPI/ServiceConfiguration.cs, DragaliaAPI/appsettings.json
- Add missing test + fixes for zena functionality
=> Add maintenance controller

.github/workflows/publish-push.yaml, DragaliaAPI.Database/DatabaseConfiguration.cs, DragaliaAPI.Database/PostgresOptions.cs, DragaliaAPI.Integration.Test/CustomWebApplicationFactory.cs, DragaliaAPI.Photon.StateManager.Test/CustomWebApplicationFactory.cs, DragaliaAPI.Photon.StateManager/Controllers/EventController.cs, DragaliaAPI.Photon.StateManager/Models/RedisCachingOptions.cs, DragaliaAPI.Photon.StateManager/Models/RedisOptions.cs, DragaliaAPI.Photon.StateManager/Program.cs, DragaliaAPI.Photon.StateManager/appsettings.json, DragaliaAPI.Test/Features/Dungeon/DungeonServiceTest.cs, DragaliaAPI.Test/Services/SessionServiceTest.cs, DragaliaAPI/Dockerfile, DragaliaAPI/DragaliaAPI.csproj, DragaliaAPI/Features/Dungeon/AutoRepeat/AutoRepeatService.cs, DragaliaAPI/Features/Dungeon/DungeonService.cs, DragaliaAPI/Models/Options/RedisCachingOptions.cs, DragaliaAPI/Models/Options/RedisOptions.cs, DragaliaAPI/Program.cs, DragaliaAPI/Services/Game/SessionService.cs, DragaliaAPI/Services/Health/HealthCheckWriter.cs, DragaliaAPI/Services/Health/RedisHealthCheck.cs, DragaliaAPI/appsettings.json, docker-compose.yml
- Add support for redis passwords
- Add support for arbitrary postgres/redis ports
=> Update config to work with nomad

.github/workflows/integration-test.yaml, PhotonStateManager/DragaliaAPI.Photon.StateManager/Program.cs, docker-compose.yml
Token change to test photonstatemanager deployment
=> Update PSM logging

.gitignore, PhotonPlugin/DragaliaAPI.Photon.Plugin.Test/DragaliaAPI.Photon.Plugin.Test.csproj, PhotonPlugin/DragaliaAPI.Photon.Plugin/DragaliaAPI.Photon.Plugin.csproj, PhotonPlugin/DragaliaAPI.Photon.Plugin/Plugins/GameLogic/GameLogicPlugin.cs, docker-compose.yml
=> Fix zena broadcasting private rooms

.github/workflows/build.yaml, .github/workflows/publish-api.yaml, DragaliaAPI/DragaliaAPI/Dockerfile, PhotonStateManager/DragaliaAPI.Photon.StateManager/Dockerfile
- Use docker build caching
- Use chiseled images
- Remove second build from Dockerfile
=> Build pipeline improvements

.github/workflows/integration-test.yaml, .github/workflows/test.yaml, Directory.Build.props, DragaliaAPI/DragaliaAPI.Database.Test/packages.lock.json, DragaliaAPI/DragaliaAPI.Database/PostgresOptions.cs, DragaliaAPI/DragaliaAPI.Database/packages.lock.json, DragaliaAPI/DragaliaAPI.Integration.Test/packages.lock.json, DragaliaAPI/DragaliaAPI.MissionDesigner/packages.lock.json, DragaliaAPI/DragaliaAPI.Shared.Test/packages.lock.json, DragaliaAPI/DragaliaAPI.Shared/packages.lock.json, DragaliaAPI/DragaliaAPI.Test.Utils/packages.lock.json, DragaliaAPI/DragaliaAPI.Test/packages.lock.json, DragaliaAPI/DragaliaAPI/DragaliaAPI.csproj, DragaliaAPI/DragaliaAPI/Program.cs, DragaliaAPI/DragaliaAPI/packages.lock.json, PhotonPlugin/DragaliaAPI.Photon.Plugin.Test/packages.lock.json, PhotonPlugin/DragaliaAPI.Photon.Plugin/packages.lock.json, PhotonStateManager/DragaliaAPI.Photon.StateManager.Test/packages.lock.json, PhotonStateManager/DragaliaAPI.Photon.StateManager/packages.lock.json, Shared/DragaliaAPI.Photon.Shared/packages.lock.json
- Disable auto-migration in CI pipeline as it's done on test start
- Move away from undocumented env variable for this and use `IConfiguration` (but still leave it undocumented 😁)
- Cache nuget package restore
=> Improve test workflow

DragaliaAPI/DragaliaAPI.Database/Repositories/UnitRepository.cs
=> Optimize UnitRepository duplicate checking

Directory.Packages.props, DragaliaAPI/DragaliaAPI.Database.Test/DragaliaAPI.Database.Test.csproj, DragaliaAPI/DragaliaAPI.Database.Test/packages.lock.json, DragaliaAPI/DragaliaAPI.Integration.Test/DragaliaAPI.Integration.Test.csproj, DragaliaAPI/DragaliaAPI.Integration.Test/packages.lock.json, DragaliaAPI/DragaliaAPI.Shared.Test/DragaliaAPI.Shared.Test.csproj, DragaliaAPI/DragaliaAPI.Shared.Test/packages.lock.json, DragaliaAPI/DragaliaAPI.Test/DragaliaAPI.Test.csproj, DragaliaAPI/DragaliaAPI.Test/packages.lock.json, PhotonPlugin/DragaliaAPI.Photon.Plugin.Test/DragaliaAPI.Photon.Plugin.Test.csproj, PhotonPlugin/DragaliaAPI.Photon.Plugin.Test/packages.lock.json, PhotonPlugin/DragaliaAPI.Photon.Plugin/packages.lock.json, PhotonStateManager/DragaliaAPI.Photon.StateManager.Test/DragaliaAPI.Photon.StateManager.Test.csproj, PhotonStateManager/DragaliaAPI.Photon.StateManager.Test/packages.lock.json
We are no longer collecting code coverage stats, so these serve no purpose
=> Remove coverlet packages

Directory.Build.props, DragaliaAPI/DragaliaAPI.Database.Test/packages.lock.json, DragaliaAPI/DragaliaAPI.Database/packages.lock.json, DragaliaAPI/DragaliaAPI.Integration.Test/packages.lock.json, DragaliaAPI/DragaliaAPI.MissionDesigner/packages.lock.json, DragaliaAPI/DragaliaAPI.Shared.Test/packages.lock.json, DragaliaAPI/DragaliaAPI.Shared/packages.lock.json, DragaliaAPI/DragaliaAPI.Test.Utils/packages.lock.json, DragaliaAPI/DragaliaAPI.Test/packages.lock.json, DragaliaAPI/DragaliaAPI/Dockerfile, DragaliaAPI/DragaliaAPI/packages.lock.json, PhotonStateManager/DragaliaAPI.Photon.StateManager.Test/packages.lock.json, PhotonStateManager/DragaliaAPI.Photon.StateManager/Dockerfile, PhotonStateManager/DragaliaAPI.Photon.StateManager/DragaliaAPI.Photon.StateManager.csproj, PhotonStateManager/DragaliaAPI.Photon.StateManager/packages.lock.json
Was missing a few required packages to be able to write logs
Also:
- Actually set analysis level to latest-minimum, clearly forgot to unstage the trial of latest-recommended during #733
- Fix dockerfiles copying everything
=> Fix PhotonStateManager logging

PhotonPlugin/DragaliaAPI.Photon.Plugin/DragaliaAPI.Photon.Plugin.csproj, PhotonPlugin/DragaliaAPI.Photon.Plugin/Plugins/GameLogic/GameLogicPlugin.cs
=> Fail join requests if game is already in progress

DragaliaAPI/DragaliaAPI/appsettings.json, PhotonStateManager/DragaliaAPI.Photon.StateManager/Program.cs
The Coalesce(StatusCode, 200) was removing all internal healthcheck logs except the response
=> Fix health check logging

DragaliaAPI/DragaliaAPI.Integration.Test/Features/Dungeon/DungeonSkipTest.cs, DragaliaAPI/DragaliaAPI/Features/Quest/QuestService.cs
=> Fix skip tickets only rewarding 1 progress to endeavours

DragaliaAPI/DragaliaAPI.Test/Controllers/DungeonControllerTest.cs, DragaliaAPI/DragaliaAPI/Features/Dungeon/DungeonController.cs, DragaliaAPI/DragaliaAPI/Features/Dungeon/Start/DungeonStartController.cs
Investigating a reported issue with dungeon fail that happens intermittently
=> Add logging to dungeon start and fail

Website/.env.development, Website/package.json, Website/playwright.config.ts, Website/src/hooks.client.ts, Website/src/hooks.server.ts, Website/src/routes/(main)/header.svelte, Website/src/routes/(main)/routes.svelte, Website/tests/__screenshots__/home.test.ts/displays-correctly-1.png, Website/tests/__screenshots__/home.test.ts/displays-correctly-on-mobile-1.png, Website/tests/__screenshots__/news.test.ts/displays-correctly-1.png, Website/tests/__screenshots__/news.test.ts/displays-correctly-on-mobile-1.png, Website/tests/home.test.ts, Website/tests/news.test.ts, Website/vite.config.ts
+ drawer improvements to close it when you change page. Slightly bugged as it doesn't play the animation but this is a known bug in vaul-svelte
=> Add news page tests

Website/.env, Website/.env.development, Website/src/mocks/handlers/user.ts, Website/src/routes/(main)/login/+page.server.ts, Website/test-results/.last-run.json
- Document env parameters
- Remove playwright dir
- Remove unneeded PUBLIC_DAWNSHARD_URL param
=> Tidy up website

.github/workflows/website.yaml, .gitignore, Website/.env, Website/.env.development, Website/src/hooks.server.ts, Website/src/mocks/handlers/handlers.ts, Website/src/routes/health/+server.ts
- Make internal URL dynamic env
- Add /health endpoint
=> Website deployment improvements

.github/workflows/publish-website.yaml, DragaliaAPI/DragaliaAPI/Features/Webview/WebviewVersionController.cs, DragaliaAPI/DragaliaAPI/Program.cs, DragaliaAPI/DragaliaAPI/appsettings.json, Website/src/hooks.server.ts, Website/src/routes/(main)/[...path]/+page.ts
- swap news webview over to new website for beta testing
=> Make allowed origins configurable

DragaliaAPI/DragaliaAPI/Features/Web/Account/UserController.cs, Website/src/mocks/handlers/handlers.ts, Website/src/routes/(main)/news/item.svelte, Website/src/routes/(main)/oauth/+page.server.ts
HEAD doesn't appear to run auth schemes and always returns 404?
=> Use HTTP GET instead of HEAD to verify user existence

DragaliaAPI/DragaliaAPI/Features/Web/Account/UserController.cs, DragaliaAPI/DragaliaAPI/Features/Web/Account/UserService.cs, DragaliaAPI/DragaliaAPI/Features/Web/WebAuthenticationHelper.cs
Mystified by `/api/user/me` invariably returning 404 on production
=> Add auth logging

Directory.Packages.props, DragaliaAPI/DragaliaAPI/DragaliaAPI.csproj
Hopefully fixes failed deploy since we will no longer have the 8.0.6 transitive dependency from Npgsql
=> Install relational package

DragaliaAPI/DragaliaAPI.Integration.Test/Features/Login/LoginTest.cs, DragaliaAPI/DragaliaAPI.Integration.Test/Features/Summoning/SummonTest.cs, DragaliaAPI/DragaliaAPI/Features/Login/Actions/DailySummoningDealResetAction.cs, DragaliaAPI/DragaliaAPI/Features/Shop/PaymentService.cs, DragaliaAPI/DragaliaAPI/Features/Summoning/SummonBannerOptions.cs, DragaliaAPI/DragaliaAPI/Features/Summoning/SummonController.cs, DragaliaAPI/DragaliaAPI/Features/Summoning/SummonRequestInfo.cs, DragaliaAPI/DragaliaAPI/Features/Summoning/SummonService.cs
- Grant 2x sigil points when using diamantium
- Limit daily deal to once per day
=> Add support for summoning with diamantium

.github/dependabot.yml, .github/workflows/build.yaml, .github/workflows/playwright-test.yaml, .github/workflows/publish-website.yaml, .github/workflows/website.yaml, DragaliaAPI.sln, DragaliaAPI/DragaliaAPI/Dockerfile, DragaliaAPI/version.json, PhotonStateManager/DragaliaAPI.Photon.StateManager/Dockerfile, Website/Dockerfile, Website/package.json, Website/pnpm-lock.yaml, Website/src/routes/+layout.svelte, Website/svelte.config.js, Website/version.json, Website/vite.config.ts
- Use nerdbank for website images
- Make main branch beta tags (release versions come from Git tags, if we ever use those again)
- Add docker label images
- Add dependabot to website docker file
=> More nerdbank

DragaliaAPI/DragaliaAPI/Features/GraphQL/ImpersionationMutations.cs
Broken due to global query filters on DbPlayerUserData probably
=> Fix user impersonation

DragaliaAPI/DragaliaAPI.Integration.Test/Features/Dungeon/DungeonRecordTest.cs, DragaliaAPI/DragaliaAPI.Integration.Test/Features/Dungeon/DungeonStartTest.cs, DragaliaAPI/DragaliaAPI.Integration.Test/Features/Quest/QuestReadStoryTest.cs, DragaliaAPI/DragaliaAPI.Integration.Test/Features/SavefileUpdate/V18UpdateTest.cs, DragaliaAPI/DragaliaAPI.Integration.Test/Features/SavefileUpdate/V1UpdateTest.cs, DragaliaAPI/DragaliaAPI.Integration.Test/Features/Tutorial/TutorialTest.cs, DragaliaAPI/DragaliaAPI.Test/Features/AbilityCrests/AbilityCrestServiceTest.cs, DragaliaAPI/DragaliaAPI.Test/Features/Dungeon/Record/DungeonRecordServiceTest.cs, DragaliaAPI/DragaliaAPI.Test/Features/Tutorial/TutorialServiceTest.cs, DragaliaAPI/DragaliaAPI.Test/Services/StoryServiceTest.cs, DragaliaAPI/DragaliaAPI/Features/AbilityCrests/AbilityCrestService.cs, DragaliaAPI/DragaliaAPI/Features/Dungeon/Record/DungeonRecordService.cs, DragaliaAPI/DragaliaAPI/Features/Dungeon/Start/DungeonStartService.cs, DragaliaAPI/DragaliaAPI/Features/GraphQL/UserDataMutations.cs, DragaliaAPI/DragaliaAPI/Features/SavefileUpdate/V15Update.cs, DragaliaAPI/DragaliaAPI/Features/SavefileUpdate/V18Update.cs, DragaliaAPI/DragaliaAPI/Features/SavefileUpdate/V1Update.cs, DragaliaAPI/DragaliaAPI/Features/SavefileUpdate/V4Update.cs, DragaliaAPI/DragaliaAPI/Features/SavefileUpdate/V7Update.cs, DragaliaAPI/DragaliaAPI/Features/Story/StoryService.cs, DragaliaAPI/DragaliaAPI/Features/Summoning/RedoableSummonController.cs, DragaliaAPI/DragaliaAPI/Features/Tutorial/FeatureExtensions.cs, DragaliaAPI/DragaliaAPI/Features/Tutorial/ITutorialService.cs, DragaliaAPI/DragaliaAPI/Features/Tutorial/TutorialController.cs, DragaliaAPI/DragaliaAPI/Features/Tutorial/TutorialService.cs, DragaliaAPI/DragaliaAPI/ServiceConfiguration.cs, DragaliaAPI/DragaliaAPI/Services/Game/TutorialService.cs
=> Fix primal dragon trials being unlocked by the wrong story

DragaliaAPI/DragaliaAPI.Integration.Test/Features/Web/Savefile/SavefileEditTests.cs, DragaliaAPI/DragaliaAPI/Features/Present/PresentController.cs, DragaliaAPI/DragaliaAPI/Features/Web/FeatureExtensions.cs, DragaliaAPI/DragaliaAPI/Features/Web/News/NewsController.cs, DragaliaAPI/DragaliaAPI/Features/Web/Savefile/SavefileController.cs, DragaliaAPI/DragaliaAPI/Features/Web/Savefile/SavefileEditController.cs, DragaliaAPI/DragaliaAPI/Features/Web/Savefile/SavefileEditRequest.cs, DragaliaAPI/DragaliaAPI/Features/Web/Savefile/SavefileEditService.cs, DragaliaAPI/DragaliaAPI/Features/Web/Users/UserController.cs, Website/.env, Website/.env.development, Website/src/routes/(main)/account/save-editor/present/presentWidget.svelte, Website/src/routes/(main)/account/save-editor/staged.svelte, Website/src/routes/(main)/routes.ts
- Implement endpoint to add presents
- Sort dropdowns
=> Finish save editor backend

DragaliaAPI/DragaliaAPI.Integration.Test/Features/Present/PresentTest.cs, DragaliaAPI/DragaliaAPI/Features/Reward/Handlers/DragonHandler.cs
Yet another fix for a bug uncovered by the editor :)
=> Fix batch grant of single entity with multiple dragons

DragaliaAPI/DragaliaAPI.Integration.Test/Features/Present/PresentTest.cs, DragaliaAPI/DragaliaAPI/Features/Reward/Handlers/GenericRewardHandler.cs, DragaliaAPI/DragaliaAPI/Features/Reward/Handlers/HustleHammerHandler.cs, DragaliaAPI/DragaliaAPI/Features/Reward/Handlers/WyrmiteHandler.cs, DragaliaAPI/DragaliaAPI/Features/Web/Savefile/EditorWidgetsService.cs, DragaliaAPI/DragaliaAPI/Features/Web/Savefile/SavefileEditService.cs, Website/src/lib/translations/en/save-editor.json, Website/src/routes/(main)/account/save-editor/present/presentTypes.ts, global.json
Add wyrmite, diamantium, and hustle hammers to the website save editor
=> Add new entity types to save editor

DragaliaAPI/DragaliaAPI/Features/Webview/WebviewVersionController.cs, Website/src/routes/(main)/news/pagination.svelte
- Fix webview ingame returning 404
- Fix unlabelled graphics document in news pages
=> Smaller news fixes

.config/dotnet-tools.json, .github/workflows/build.yaml, .github/workflows/integration-test.yaml, .github/workflows/lint.yaml, .github/workflows/test.yaml, Aspire/Dawnshard.AppHost/Dawnshard.AppHost.csproj, Aspire/Directory.Build.props, Directory.Packages.props, DragaliaAPI/Directory.Build.props, DragaliaAPI/DragaliaAPI/Dockerfile, DragaliaAPI/DragaliaAPI/Extensions/EnumerableExtensions.cs, DragaliaAPI/DragaliaAPI/Features/GraphQL/Schema.cs, DragaliaAPI/DragaliaAPI/Features/StorySkip/StorySkipService.cs, PhotonStateManager/Directory.Build.props, PhotonStateManager/DragaliaAPI.Photon.StateManager.Test/DragaliaAPI.Photon.StateManager.Test.csproj, PhotonStateManager/DragaliaAPI.Photon.StateManager/Dockerfile, PhotonStateManager/DragaliaAPI.Photon.StateManager/DragaliaAPI.Photon.StateManager.csproj, global.json
- Retarget DragaliaAPI and PhotonStateManager to net9.0
- Upgrade all packages
- Remove ToHashSetAsync as this is now provided by EF Core
- Fix weird delegate type inference error
AsEnumerable to handle EF regressions
=> Upgrade to .NET 9

DragaliaAPI/DragaliaAPI.MasterAssetConverter/DragaliaAPI.MasterAssetConverter.csproj, DragaliaAPI/DragaliaAPI.Shared.SourceGenerator.Test/DragaliaAPI.Shared.SourceGenerator.Test.csproj, DragaliaAPI/DragaliaAPI.Shared/DragaliaAPI.Shared.csproj
=> Fix remaining net8.0 projects

DragaliaAPI/DragaliaAPI.Integration.Test/Features/Missions/MissionTest.cs, DragaliaAPI/DragaliaAPI/Features/Missions/MissionProgressionService.cs
Focused on the harder case of overleveling when implementing these, forgot to add a test for hitting the level exactly
=> Fix off-by-one error when completing Royal Regiment level mission

Aspire/Dawnshard.AppHost/Program.cs, Aspire/Dawnshard.AppHost/appsettings.json, PhotonPlugin/DragaliaAPI.Photon.Plugin/DragaliaAPI.Photon.Plugin.csproj, PhotonPlugin/DragaliaAPI.Photon.Plugin/Plugins/GameLogic/Events/CharacterData.cs, PhotonPlugin/DragaliaAPI.Photon.Plugin/Plugins/GameLogic/Events/ClearQuestRequest.cs, PhotonPlugin/DragaliaAPI.Photon.Plugin/Plugins/GameLogic/Events/ClearQuestResponse.cs, PhotonPlugin/DragaliaAPI.Photon.Plugin/Plugins/GameLogic/Events/DebugInspectionRequest.cs, PhotonPlugin/DragaliaAPI.Photon.Plugin/Plugins/GameLogic/Events/EventBase.cs, PhotonPlugin/DragaliaAPI.Photon.Plugin/Plugins/GameLogic/Events/PartyEvent.cs, PhotonPlugin/DragaliaAPI.Photon.Plugin/Plugins/GameLogic/GameLogicPlugin.cs, PhotonPlugin/DragaliaAPI.Photon.Plugin/Plugins/GameLogic/GoToIngameState.cs, PhotonPlugin/DragaliaAPI.Photon.Plugin/Plugins/GameLogic/GoToIngameStateManager.cs, PhotonPlugin/DragaliaAPI.Photon.Plugin/Plugins/GameLogic/HeroParamExData.cs, PhotonPlugin/DragaliaAPI.Photon.Plugin/Plugins/Gluon/GluonPluginFactory.cs, PhotonPlugin/DragaliaAPI.Photon.Plugin/Plugins/StateManager/StateManagerPlugin.cs, PhotonPlugin/DragaliaAPI.Photon.Plugin/Shared/Helpers/CollectionExtensions.cs, PhotonPlugin/DragaliaAPI.Photon.Plugin/Shared/Helpers/DtoHelpers.cs, PhotonPlugin/DragaliaAPI.Photon.Plugin/Shared/Helpers/PluginHostExtensions.cs, PhotonPlugin/DragaliaAPI.Photon.Plugin/Shared/Models/RoomEntryCondition.cs, PhotonPlugin/DragaliaAPI.Photon.Plugin/Shared/PluginConfiguration.cs, PhotonStateManager/DragaliaAPI.Photon.StateManager/Program.cs
Adds the ability to run Photon Server using the Asprie AppHost.
Also tidies up some nullability warnings inside the plugin and updates it to conform with the new version of MessagePack.CSharp.
=> Enrol Photon in .NET Aspire orchestration

.husky/task-runner.json, DragaliaAPI/DragaliaAPI.Database/Entities/DbPlayer.cs, DragaliaAPI/DragaliaAPI.Database/Entities/DbPlayerUserData.cs, DragaliaAPI/DragaliaAPI.Database/Migrations/20250101115256_expand_players_table.Designer.cs, DragaliaAPI/DragaliaAPI.Database/Migrations/20250101115256_expand_players_table.cs, DragaliaAPI/DragaliaAPI.Database/Repositories/IUserDataRepository.cs, DragaliaAPI/DragaliaAPI.Database/Repositories/UserDataRepository.cs, DragaliaAPI/DragaliaAPI.Integration.Test/CustomWebApplicationFactory.cs, DragaliaAPI/DragaliaAPI.Integration.Test/Features/Dungeon/DungeonStartTest.cs, DragaliaAPI/DragaliaAPI.Integration.Test/Features/Login/SavefileImportTest.cs, DragaliaAPI/DragaliaAPI.Integration.Test/Features/Login/ToolTest.cs, DragaliaAPI/DragaliaAPI.Integration.Test/Features/Web/Savefile/SavefileExportTests.cs, DragaliaAPI/DragaliaAPI.Integration.Test/Features/Web/Users/UserTests.cs, DragaliaAPI/DragaliaAPI.Integration.Test/TestContainersHelper.cs, DragaliaAPI/DragaliaAPI/Features/Login/Actions/DailySummoningDealResetAction.cs, DragaliaAPI/DragaliaAPI/Features/Login/Auth/AuthService.cs, DragaliaAPI/DragaliaAPI/Features/Login/Savefile/SavefileService.cs, DragaliaAPI/DragaliaAPI/Features/Web/Users/User.cs, DragaliaAPI/DragaliaAPI/Features/Web/Users/UserService.cs, DragaliaAPI/DragaliaAPI/Mapping/AutoMapper/UserDataReverseMapProfile.cs, Website/src/routes/(main)/account/profile/renderDate.ts, Website/src/routes/(main)/account/profile/saveImport.svelte, Website/src/routes/(main)/account/profile/userInformation.svelte, Website/src/routes/(main)/account/profile/userProfile.ts
=> Expand players table

Aspire/Dawnshard.AppHost/Program.cs, Directory.Packages.props, DragaliaAPI/DragaliaAPI.Database.Test/DbTestFixture.cs, DragaliaAPI/DragaliaAPI.Integration.Test/DragaliaAPI.Integration.Test.csproj, DragaliaAPI/DragaliaAPI.Integration.Test/Features/Dungeon/DungeonStartTest.cs, DragaliaAPI/DragaliaAPI.Integration.Test/Other/MetricsTest.cs, DragaliaAPI/DragaliaAPI.Integration.Test/TestFixture.cs, DragaliaAPI/DragaliaAPI.Test/Features/Shared/UpdateDataServiceTest.cs, DragaliaAPI/DragaliaAPI.Test/RepositoryTestFixture.cs, DragaliaAPI/DragaliaAPI/DragaliaAPI.csproj, DragaliaAPI/DragaliaAPI/Features/Dungeon/Record/DungeonRecordController.cs, DragaliaAPI/DragaliaAPI/Features/Login/Savefile/ISavefileService.cs, DragaliaAPI/DragaliaAPI/Features/Login/Savefile/SavefileService.cs, DragaliaAPI/DragaliaAPI/Features/Web/Savefile/SavefileController.cs, DragaliaAPI/DragaliaAPI/Features/Web/Savefile/SavefileEditController.cs, DragaliaAPI/DragaliaAPI/Infrastructure/Metrics/DragaliaApiMetrics.cs, DragaliaAPI/DragaliaAPI/Infrastructure/Metrics/IDragaliaApiMetrics.cs, DragaliaAPI/DragaliaAPI/Models/Generated/LoadIndexResponse.cs, DragaliaAPI/DragaliaAPI/ServiceConfiguration.cs, PhotonStateManager/DragaliaAPI.Photon.StateManager.Test/DragaliaAPI.Photon.StateManager.Test.csproj, PhotonStateManager/DragaliaAPI.Photon.StateManager.Test/Other/MetricsTest.cs, PhotonStateManager/DragaliaAPI.Photon.StateManager/PhotonStateManagerMetrics.cs, PhotonStateManager/DragaliaAPI.Photon.StateManager/Program.cs, PhotonStateManager/DragaliaAPI.Photon.StateManager/ServiceConfiguration.cs
Closes #1213 
Adds some custom metrics that could be of potential interest
=> Add custom metrics

Website/playwright.config.ts, Website/src/app.html, Website/src/hooks.server.ts, Website/src/routes/(main)/+layout.svelte, Website/src/routes/csp/+server.ts, Website/svelte.config.js
The mode-watcher bug causing a flash of light mode has been fixed so we can now add a CSP.
Still need to add an additional directive due to a Svelte bug
=> Add Content-Security-Policy

Website/src/hooks.server.ts
Contributes to https://github.com/SapiensAnatis/Dawnshard/issues/1265. Adds some debugging information around fetch requests.
=> Log fetch requests

DragaliaAPI/DragaliaAPI.Test/Features/Fort/BonusServiceTest.cs, DragaliaAPI/DragaliaAPI.Test/Features/Shared/UpdateDataServiceTest.cs, DragaliaAPI/DragaliaAPI/Features/Friends/FriendNotificationService.cs, DragaliaAPI/DragaliaAPI/Features/Missions/MissionProgressionService.cs, DragaliaAPI/DragaliaAPI/Features/Missions/MissionService.cs, DragaliaAPI/DragaliaAPI/Features/Shared/UpdateDataService.cs, DragaliaAPI/DragaliaAPI/ServiceConfiguration.cs
Adds some custom tracing activities to shed light on some performance issues. Contributes to #1282
=> Add custom activities

DragaliaAPI/DragaliaAPI/Features/Parties/PartyController.cs
Attempting to track down an issue with wrong team data being sent back with "Team data has been updated"
=> Add logging around party updates

DragaliaAPI/DragaliaAPI.Integration.Test/Features/Wall/WallStartTest.cs, DragaliaAPI/DragaliaAPI/Features/Wall/WallService.cs
=> Handle partially initialized wall

Directory.Packages.props, DragaliaAPI/DragaliaAPI/Features/Friends/StaticHelperDataService.cs
Plus extra commit to build on my new environment with an earlier version of the .NET SDK
=> Fix helper ID collision
