SapiensAnatis/Dawnshard

DragaliaAPI.Database.Test/DbTestFixture.cs
DragaliaAPI.Database.Test/Repositories/DeviceAccountRepositoryTest.cs
DragaliaAPI.Database.Test/Repositories/PartyRepositoryTest.cs
DragaliaAPI.Database.Test/Repositories/QuestRepositoryTest.cs
DragaliaAPI.Database.Test/Repositories/SummonRepositoryTest.cs
DragaliaAPI.Database.Test/Repositories/UnitRepositoryTest.cs
DragaliaAPI.Database.Test/Repositories/UserDataRepositoryTest.cs
DragaliaAPI.Database/Repositories/DeviceAccountRepository.cs
DragaliaAPI.Database/Repositories/IDeviceAccountRepository.cs
DragaliaAPI.Database/Repositories/IInventoryRepository.cs
DragaliaAPI.Database/Repositories/InventoryRepository.cs
DragaliaAPI.Test/Integration/IntegrationTestFixture.cs
DragaliaAPI.Test/Integration/Other/DeleteSavefileTest.cs
DragaliaAPI.sln
DragaliaAPI/Controllers/Dragalia/DungeonRecordController.cs
DragaliaAPI/Controllers/Dragalia/ItemController.cs
DragaliaAPI/Controllers/Dragalia/SummonController.cs
DragaliaAPI/Models/AutoMapper/InventoryMapProfile.cs
DragaliaAPI/Models/Generated/Components.cs

- Gives players a selection of maxed out wyrmprints, dragons, and weapons upon creating a savefile 
- Drops a random selection of upgrade materials from all quests
- Adds ItemController and `item/get_list` to view material info
- Misc. tidying up and fixes in:
- SummonController
- DungeonRecordController
- DeveloperAuthorization
The hope is that with these default items, it won't be necessary to import a savefile to test most functionality of the server -- though many players will probably still want to do so.

Pre-public release enhancements

---

DragaliaAPI.Test/Integration/Dragalia/VersionTest.cs
DragaliaAPI/Controllers/Dragalia/VersionController.cs

iOS users previous would 404 as the game attempts to download an iOS manifest that doesn't exist. Correctly switch the resource version string that is sent by /version/get_resource_version based on platform ID to fix this.

Fix resource version string when attempting to connect on iOS

---

DragaliaAPI.Database/Factories/DbPlayerCharaDataFactory.cs
DragaliaAPI/Models/AutoMapper/UnitMapProfile.cs

Closes #64 
Story characters will have their shared skills unlocked by default when being added (not backwards compatible)
Weapon skills and abilities are always set to the max level but this will need to be revisited when weapon upgrading is implemented. These values are not tracked in the database because they are not sent by /load/index, so presumably they're calculated on the fly.  Additionally, skill_no is always set to 1 because I am unsure what this does, however it appears to work with Agito/PDT weapons just fine.

Shared skill fix

---

DragaliaAPI.Database/Entities/DbAbilityCrest.cs
DragaliaAPI.Database/Entities/DbParty.cs
DragaliaAPI.Database/Entities/DbWeaponBody.cs
DragaliaAPI.Database/Migrations/20221229004711_develop_2.Designer.cs
DragaliaAPI.Database/Migrations/20221229004711_develop_2.cs

Valid savefiles were experiencing import failures. Turns out the game lets you have 20 characters, not 16. Boosted it to 64 just in case; it (probably) won't do any harm to store ones that may be longer. Example from fudging the db:
The client should never send a request containing a name over 20 characters anyway.

Increase party name length limit

---

DragaliaAPI.Database/Entities/DbDeviceAccount.cs
DragaliaAPI.Database/Entities/DbQuest.cs
DragaliaAPI.Database/Entities/DbTalisman.cs
DragaliaAPI.Database/Migrations/20230101060732_develop_3.Designer.cs
DragaliaAPI.Database/Migrations/20230101060732_develop_3.cs
DragaliaAPI.Test/Integration/Dragalia/UserTest.cs
DragaliaAPI.Test/Integration/Nintendo/NintendoLoginTest.cs
DragaliaAPI/Controllers/Dragalia/UserController.cs
DragaliaAPI/Controllers/Nintendo/NintendoLoginController.cs
DragaliaAPI/Models/AutoMapper/QuestReverseMapProfile.cs
DragaliaAPI/Models/AutoMapper/UnitReverseMapProfile.cs
DragaliaAPI/Services/AuthService.cs

- Make the NintendoLoginController return 419 if BaaS login is enabled to block old patched clients
- Add additional logging around id tokens in AuthService
- Remove foreign key DbDeviceAccount constraint on DbTalisman and DbQuest as this table is no longer used

Baas fixes

---

DragaliaAPI.Database/DatabaseConfiguration.cs
DragaliaAPI.Database/Entities/DbPlayerStoryState.cs
DragaliaAPI.Database/Repositories/IInventoryRepository.cs
DragaliaAPI.Database/Repositories/IStoryRepository.cs
DragaliaAPI.Database/Repositories/IUserDataRepository.cs
DragaliaAPI.Database/Repositories/InventoryRepository.cs
DragaliaAPI.Database/Repositories/StoryRepository.cs
DragaliaAPI.Database/Repositories/UserDataRepository.cs
DragaliaAPI.Test/Integration/Dragalia/CastleStoryTest.cs
DragaliaAPI.Test/Integration/Dragalia/StoryTest.cs
DragaliaAPI.Test/Unit/Controllers/DungeonRecordControllerTest.cs
DragaliaAPI.Test/Unit/Services/UpdateDataServiceTest.cs
DragaliaAPI/Controllers/Dragalia/CastleStoryController.cs
DragaliaAPI/Controllers/Dragalia/DungeonRecordController.cs
DragaliaAPI/Controllers/Dragalia/StoryController.cs
DragaliaAPI/Services/SavefileService.cs
DragaliaAPI/Services/UpdateDataService.cs

- Adds endpoints for unit and castle stories
- These currently add 25/50 wyrmite directly but will need to be updated later to use the gift box
- Castle stories deduct looking glasses; give new savefiles 100 of these and add to quest drop table to enable testing
- Currently no API validation on story availability

Add unit and castle stories

---

DragaliaAPI/Program.cs

Quick change to add compression to responses, which appears to work and should make latency a bit better.
Not likely to solve #88 as that timing window is request processing and has nothing to do with the transit time that this will affect.

Add response compression

---

DragaliaAPI.Test/Integration/Other/SavefileImportTest.cs
DragaliaAPI/Models/AutoMapper/UnitMapProfile.cs
DragaliaAPI/Pages/News.cshtml
DragaliaAPI/Services/AuthService.cs
DragaliaAPI/appsettings.Testing.json

- Auto-set wyrmprints abilities as level 3; closes #78. Issue #96 raised to do this properly later.
- Update news page
- Add an enrich statement to AuthService to include the account id, enabling this to be logged for the first login where the SessionLookupMiddleware has not been used

Wyrmprint fix + misc tweaks

---

DragaliaAPI/Services/SavefileService.cs

Fix typo in key id retaining mechanism which was causing kaleido prints to still be erased.
Would be nice to have tests around this behaviour, but it is quite difficult to assert on as they change unpredictably.

Save import fix

---

DragaliaAPI.Database/Repositories/IUnitRepository.cs
DragaliaAPI.Database/Repositories/UnitRepository.cs
DragaliaAPI.Test/TestUtils.cs
DragaliaAPI.Test/Unit/Controllers/DungeonStartControllerTest.cs
DragaliaAPI.Test/Unit/Services/AuthServiceTest.cs
DragaliaAPI.Test/Unit/Services/DungeonServiceTest.cs
DragaliaAPI.Test/Unit/Services/SessionServiceTest.cs
DragaliaAPI/Controllers/Dragalia/CharaController.cs
DragaliaAPI/Controllers/Dragalia/DungeonStartController.cs
DragaliaAPI/Controllers/Dragalia/RedoableSummonController.cs
DragaliaAPI/Controllers/Dragalia/SummonController.cs
DragaliaAPI/Controllers/DragaliaControllerBase.cs
DragaliaAPI/Controllers/Nintendo/NintendoLoginController.cs
DragaliaAPI/GlobalSuppressions.cs
DragaliaAPI/Middleware/AccountIdEnricher.cs
DragaliaAPI/Middleware/CustomClaimType.cs
DragaliaAPI/Middleware/SessionAuthenticationHandler.cs
DragaliaAPI/Models/Options/RedisOptions.cs
DragaliaAPI/Models/Session.cs
DragaliaAPI/Program.cs
DragaliaAPI/Services/AuthService.cs
DragaliaAPI/Services/DungeonService.cs
DragaliaAPI/Services/ISessionService.cs
DragaliaAPI/Services/SessionService.cs
DragaliaAPI/appsettings.json

Should enable logs to be traced back to a user more easily (without a DB query) as they can provide their viewer ID due to it being publically visible.
Accomplished via adding it to the Session in Redis.
Also:
- Uses Serilog.Expressions for logging now that we have more properties to make it neater
- Adds modern SessionService tests
- Various Redis tweaks around config

Add viewer id to logs

---

DragaliaAPI/Controllers/Dragalia/RedoableSummonController.cs
DragaliaAPI/Middleware/SessionAuthenticationHandler.cs
DragaliaAPI/Services/SessionService.cs

If your session expired, you get kicked out of SessionAuthenticationHandler with a SessionException to get a new token. Problem is that /tool/auth has to go through there too. So you would never be able to get into AuthService to make a new session. Fix that by allowing SessionErrors for AllowAnonymous controllers.

Fix infinite session loop

---

DragaliaAPI/DragaliaAPI.csproj
DragaliaAPI/appsettings.Development.json
DragaliaAPI/appsettings.json
docker-compose.yml

Adds the packages for Seq logging. This is not in the helm chart unless enabled and requires admins to install the Seq chart themselves

Add Seq logging

---

DragaliaAPI.Database.Test/DbTestFixture.cs
DragaliaAPI.Test/Integration/Dragalia/ToolTest.cs
DragaliaAPI.Test/Integration/IntegrationTestFixture.cs
DragaliaAPI.Test/Unit/Helpers/BaasRequestHelperTest.cs
DragaliaAPI.Test/Unit/Services/AuthServiceTest.cs
DragaliaAPI/Controllers/Other/SavefileController.cs
DragaliaAPI/Services/AuthService.cs
DragaliaAPI/Services/Helpers/BaasRequestHelper.cs
DragaliaAPI/Services/ISavefileService.cs
DragaliaAPI/Services/SavefileService.cs

If a save import took a long time, the client would re-call `/tool/auth` again before receiving a response.. This would trigger another save import while the existing one was running and lead to a DbConcurrencyException.
This PR:
- Adds a locking mechanism by setting a string derived from the account ID in Redis
- If a subsequent request is received, and a matching ID string is in Redis, no import is attempted and the Task is simply to wait until this key disappears
- Also converts `BaasRequestHelper` to use Redis to cache the jwks, thus making the main application truly stateless again.

Fix savefile import DbConcurrencyException

---

DragaliaAPI.Database/Entities/DbPlayerCharaData.cs

fixes summoned characters not having coabilities causing trying to unlock coab levels to fail

Set ExAbility level defaults to 1

---

DragaliaAPI.Test/Integration/Other/AuthorizationMiddlewareTest.cs
DragaliaAPI.Test/Integration/Other/DeleteSavefileTest.cs
DragaliaAPI.Test/Integration/Other/ExceptionHandlerMiddlewareTest.cs
DragaliaAPI.Test/Integration/Other/SavefileImportTest.cs
DragaliaAPI.Test/Unit/Services/AuthServiceTest.cs
DragaliaAPI/Controllers/Dragalia/WebviewVersionController.cs
DragaliaAPI/Controllers/Other/TestController.cs
DragaliaAPI/Middleware/ExceptionHandlerMiddleware.cs
DragaliaAPI/Middleware/SessionAuthenticationHandler.cs
DragaliaAPI/Models/AutoMapper/UserDataMapProfile.cs
DragaliaAPI/Program.cs
DragaliaAPI/Services/AuthService.cs

- Distinguish between ID token expiry and session expiry, and return responses that will re-login or re-auth respectively
- Use HandleChallengeAsync in SessionAuthenticationHandler over a branch in ExceptionHandlerMiddleware to clean up the code
- Add integration tests for the middleware

Middleware enhancements

---

DragaliaAPI.Database/Entities/DbParty.cs
DragaliaAPI.Database/Entities/DbPlayerUserData.cs
DragaliaAPI.Database/Migrations/20230125000614_1-1-0_alpha_4.Designer.cs
DragaliaAPI.Database/Migrations/20230125000614_1-1-0_alpha_4.cs
DragaliaAPI/Models/Generated/Components.cs
DragaliaAPI/Models/Generated/LoadIndexData.cs
DragaliaAPI/Models/Generated/Requests.cs
DragaliaAPI/Services/SavefileService.cs

This is by no means exhaustive but the focus for now is limiting the length of strings, particularly those which may end up in the database -- Postgres is ridiculously forgiving with its TEXT type.
One other area worth looking at it party numbers and unit positions, these will put the DB In a funny state but are unlikely to cause any issues for users beyond the one with the invalid data.

Add basic property validation

---

DragaliaAPI.Database.Test/Repositories/InventoryRepositoryTest.cs
DragaliaAPI.Database/ApiContext.cs
DragaliaAPI.Database/Repositories/InventoryRepository.cs
DragaliaAPI.Test/Integration/Dragalia/PartyTest.cs
DragaliaAPI.Test/Integration/IntegrationTestFixture.cs
DragaliaAPI.Test/Integration/Other/SavefileImportTest.cs
DragaliaAPI/Controllers/Dragalia/DeployController.cs
DragaliaAPI/Controllers/Dragalia/PartyController.cs
DragaliaAPI/Controllers/Dragalia/SummonController.cs
DragaliaAPI/Controllers/Dragalia/VersionController.cs
DragaliaAPI/Models/AutoMapper/UserDataMapProfile.cs
DragaliaAPI/Models/Generated/LoadIndexData.cs
DragaliaAPI/Services/AuthService.cs
DragaliaAPI/Services/SavefileService.cs
docker-compose.yml

- Fixes GetMaterial not filtering by account id -- closes #104 
- Adds tests for InventoryRepository
- Adds new_get_entity_list to /summon/request response.  Further investigation required on #90 to see if this fixes
- For better visibility of #112 , returns a proper result code response from /party/set_party_setting rather than HTTP 400
- Maps everyone's level from 200 so that stamina is maxed out, enabling players w/o a save import to play endgame quests
- Makes party_list a required property in the save as importing a save without this leads to a softlock

Fix InventoryRepository issue

---

DragaliaAPI.Test/Integration/Dragalia/ToolTest.cs
DragaliaAPI/Middleware/ExceptionHandlerMiddleware.cs

Patch fix for #115 pending actual investigation. Makes SecurityTokenExpiredException boot to title screen instead of trying to refresh silently 'the cool way'.

Disable token refresh 400 response

---

DragaliaAPI/Middleware/NotFoundHandlerMiddleware.cs
DragaliaAPI/Program.cs

Adds middleware to handle 404 errors so that these do not cause a kick to the title screen. Replaces it with a result_code response that instances a pop-up which can simply be closed.

Add 404 handling middleware

---

DragaliaAPI.Test/Integration/Other/ExceptionHandlerMiddlewareTest.cs
DragaliaAPI/Middleware/ExceptionHandlerMiddleware.cs
DragaliaAPI/Services/AuthService.cs
DragaliaAPI/Services/SavefileService.cs

Noticed a PK conflict in Players when a new player joins using a save that's invalid and goes into the creating savefile code. Not sure of the cause, but attempt to address it by:
- Explicitly rolling back the transaction on save import errors
- Deleting savefile on creating a new one and add debug logging.
Also:
- Cleans up the code for handling cancelled requests in ExceptionHandlerMiddleware

Save import fixes

---

DragaliaAPI.Database.Test/Repositories/FortRepositoryTest.cs
DragaliaAPI.Test/Integration/Dragalia/FortTest.cs
DragaliaAPI.Test/Integration/Other/DeleteSavefileTest.cs
DragaliaAPI.Test/Unit/Services/UpdateDataServiceTest.cs
DragaliaAPI/Pages/News.cshtml
DragaliaAPI/Services/SavefileService.cs

Closes #118 
Need to update this whenever the tutorial can be naturally progressed to unlocking Halidom to add it there. Current implementation will not address the issue of importing a save without a halidom (which they don't until you complete that part of the tutorial)

Add halidom by default

---

DragaliaAPI.Database.Test/Repositories/WeaponRepositoryTest.cs
DragaliaAPI.Database/Repositories/InventoryRepository.cs
DragaliaAPI.Database/Repositories/UserDataRepository.cs
DragaliaAPI.Database/Repositories/WeaponRepository.cs
DragaliaAPI.Test/Unit/Services/DungeonServiceTest.cs
DragaliaAPI/Services/DungeonService.cs
DragaliaAPI/Services/WeaponService.cs

- Checks if a weapon skin is owned before adding it, due to the possibility of the save editor adding all skins but not all weapons
- Possibly fixes a random bug that sometimes happens with dungeon keys not being found
- Logging adjustments

Fix duplicate weapon skin bug

---

DragaliaAPI.Database/Entities/DbPlayerCharaData.cs
DragaliaAPI/Controllers/Dragalia/LoginController.cs

Also fixes a 500 when webcrawlers call /login due to ambiguous route -- defines it explicitly as a 404 endpoint. In practice it will always return 400 as the caller will fail SessionAuthentication

Properly unlock shared skills for story characters

---

DragaliaAPI.Test/Integration/Dragalia/DragonTest.cs
DragaliaAPI.Test/Unit/Services/DragonServiceTest.cs
DragaliaAPI/Services/DragonService.cs

Fixes:
- dragon sell income calculated incorrectly when selling more than 1 dragon of the same type
- dragon sell income calculated incorrectly when selling unbound dragons

Dragon sell income fix

---

.gitignore
DragaliaAPI/Controllers/Dragalia/SummonController.cs

Turns out we were not sending dragons in `new_get_entity_list` unless their `is_new` was `true`, i.e. they had been obtained for the first time. This is not the correct behaviour because you can receive new dragons that are duplicates of existing owned ones.
Additionally, we were rewarding eldwater for dragons which does not make any sense either.
Potentially closes #90

Potential summon fix

---

DragaliaAPI.Integration.Test/Dragalia/FortTest.cs
DragaliaAPI/Services/FortService.cs

This was causing a primary key exception due to FortService attempting to add a build that already existed:

Fix for levelling up level 1 buildings

---

DragaliaAPI.Photon.Plugin/Constants/ActorPropertyKeys.cs
DragaliaAPI.Photon.Plugin/GluonPlugin.cs
DragaliaAPI.Photon.StateManager.Test/Event/GameLeaveTest.cs
DragaliaAPI.Photon.StateManager.Test/Get/ByIdTest.cs
DragaliaAPI.Photon.StateManager.Test/Get/GameListTest.cs
DragaliaAPI.Photon.StateManager/Controllers/EventController.cs
DragaliaAPI.Photon.StateManager/Controllers/GetController.cs
DragaliaAPI.Photon.StateManager/Models/RedisGame.cs

- Don't delete the room on start, as Photon will request to remove players from it after it concludes.
- Instead, make it invisible by setting the `MatchingType` property
- Remove the Visible property as we can hide rooms using `MatchingType.NoDisplay`. 
- Change this logic so only the host calls the state manager to do this.
- Handle duplicate leave events from Photon by setting a flag to ensure only one leave request per player is sent to the state manager

Fix game leave events

---

DragaliaAPI.Integration.Test/Dragalia/MatchingTest.cs
DragaliaAPI/Services/Photon/MatchingService.cs

Fixes errors seen in Seq about 'sequence containing no element' in MapRoomList. Most likely due to a failed DB query. Since these are only for deocrating the room UI element, it's probably OK to fallback on defaults.

Fix 'sequence contains no element' error in MatchingService

---

.github/workflows/test.yaml
README.md

- Don't upload to codecov as we no longer wish to enforce code coverage statistics
- Instead upload coverage reports as an artefact for optional viewing

Disable codecov

---

DragaliaAPI/Controllers/Dragalia/QuestController.cs
DragaliaAPI/Resources/news.json

Caused by a subtle difference in the response objects between `/quest/get_quest_clear_party` and `/quest/get_quest_clear_party_multi`. 
Also updates the news (finally) with mention of co-op.

Fix edit team button not working in some quests

---

DragaliaAPI.Test/Controllers/FortControllerTest.cs
DragaliaAPI/Controllers/Dragalia/FortController.cs

Fix LevelupEnd InvalidOperationException on missing smithy

---

DragaliaAPI/Features/Present/PresentControllerService.cs

Noticed a few issues with it smoke-testing in prod, change it to be more like the other paging logic for present_list and see if that fixes it -- if not, oh well

Update paging logic for present history

---

DragaliaAPI/Services/Api/BaasApi.cs
DragaliaAPI/Services/Api/IBaasApi.cs
DragaliaAPI/Services/Game/AuthService.cs
DragaliaAPI/Services/Game/SavefileService.cs

- Gracefully handle duplicate dragon/talisman key ids in party mapping logic
- Reduce logging severity:
- Known user error on save import (JsonException/AutoMapper exception): Warning -> Information
- Unknown error on save import (primary keys etc): Error -> Warning
- Null savefile from BaaS: Error -> Information

Save import adjustments

---

DragaliaAPI.Test/Controllers/DungeonRecordControllerTest.cs
DragaliaAPI/Features/Dungeon/DungeonRecordController.cs
DragaliaAPI/Features/Dungeon/QuestEnemyService.cs

A -Infinity quest drop difficulty multiplier could occur when a quest's difficulty was less than 1000. Now the minimum difficulty multiplier will be 1

Fix being unable to clear early campaign stages

---

DragaliaAPI.Shared/Resources/Missions/MissionProgressionInfo.json

Fix incorrect wyrmprint augment mission param

---

DragaliaAPI.Integration.Test/Features/Present/PresentTest.cs
DragaliaAPI/Features/Present/PresentControllerService.cs

- Change page size / 'Claim All' count to 100
- Sort presents in descending order of ID (i.e. descending order of date received). This was already being done for present history and is how data was sent on official servers.
Closes #348

Fix present box user pains

---

DragaliaAPI.Photon.Plugin/Constants/ActorPropertyKeys.cs
DragaliaAPI.Photon.Plugin/Constants/GamePropertyKeys.cs
DragaliaAPI.Photon.Plugin/GluonPlugin.cs
DragaliaAPI/Services/Game/BonusService.cs

Closes #361 and closes #362 
Also move SetGameState call above `base.OnLeave` call to prevent `Plugin GluonPlugin tries to set game state after call to 'Continue'` error.
---
The root cause of both issues was the `StartQuest` property not being cleared between quest attempts, causing an early start and the proper data to not be received. This is a plugin-only property we use to decide when all players are loaded and to fire the StartQuest event.
However, when clearing `StartQuest` on a quest retry, the host appears to progress through the `GoToIngameState` values _much_ faster than other players. This leads to other players experiencing an infinite load, as they never receive the required events -- which probably lead to #362 since by not clearing `StartQuest` they would be forced to load …

Fix co-op retry bugs

---

DragaliaAPI.Photon.Plugin/GluonPlugin.cs
DragaliaAPI.Test/Controllers/DungeonControllerTest.cs
DragaliaAPI/Features/Dungeon/DungeonController.cs
DragaliaAPI/Features/Dungeon/Record/DungeonRecordHelperService.cs
DragaliaAPI/Services/Photon/MatchingService.cs

Closes #378 
Correctly setting is_host from /dungeon/fail makes only the host call GameSucceed, and then the plugin can use the existing OnGameSucceed logic.
Also sets support info correctly from this endpoint.

Fix failed retry votes on wipe

---

DragaliaAPI.Photon.Plugin/GluonPlugin.cs
DragaliaAPI.Photon.Plugin/Models/ActorState.cs
DragaliaAPI.Photon.StateManager/Authentication/PhotonAuthenticationHandler.cs
DragaliaAPI.Photon.StateManager/Controllers/EventController.cs
DragaliaAPI/Middleware/PhotonAuthenticationHandler.cs

- Don't call to set room visibility to false on RoomBroken. Requesting visibility changes when the room is about to tear down seems to cause a fair few errors about the game not existing. Delegate this responsibility to the StateManager.
- Remove RemovedFromRedis flag in actor state. This was causing rooms to be perpetually full as the actor state was removed before this was checked
- Set EmptyRoomTTL to 500ms (previously 30 seconds!). It's not 0 to accomodate any outgoing GameLeave etc requests.
Also:
- Fix some debug logging
- Use TryParse in auth handlers over try/catch

Modify statemanager logic around leaving and closing rooms

---

DragaliaAPI.Integration.Test/Features/Fort/FortTest.cs
DragaliaAPI.Test/Features/Fort/FortControllerTest.cs
DragaliaAPI/Features/Fort/FortController.cs
DragaliaAPI/Features/Fort/FortService.cs
DragaliaAPI/Features/Fort/IFortService.cs

- Move determination of smithy and halidom level to after SaveChangesAsync in LevelupAtOnce and LevelupEnd. This should cause the levels to be up to date if the building being levelled up is the halidom or smithy.
- Write new method to get these core levels instead of querying all builds

Fix smithy and weapon upgrades being locked incorrectly

---

DragaliaAPI/Features/DmodeDungeon/DmodeDungeonService.cs

- Always spawn max enemy count to increase menace rate. Precise wave-based spawning to be added later.
- Give players a 5-level headstart when skipping floors

Kaleidoscape tweaks

---

DragaliaAPI.Photon.Plugin/DragaliaAPI.Photon.Plugin.csproj
DragaliaAPI.Photon.Plugin/GluonPlugin.cs
DragaliaAPI.sln
DragaliaAPI/Features/TimeAttack/Validation/TalismanValidator.cs
DragaliaAPI/RazorComponents/TimeAttack/OwnClear.razor

- Actually fix OwnClear ranking -- need to include players to use the players hash
- Fix all quests showing TA ranking message
- Fix single-ability Kaleidoscape prints failing validation

More time attack fixes

---

DragaliaAPI.Database/DbTimeAttackClear.cs
DragaliaAPI.Database/Entities/DbTimeAttackClearUnit.cs
DragaliaAPI.Database/Entities/DbTimeAttackPlayer.cs
DragaliaAPI.Database/Migrations/20231006174740_time-attack-fix.Designer.cs
DragaliaAPI.Database/Migrations/20231006174740_time-attack-fix.cs
DragaliaAPI.Integration.Test/Features/Dungeon/DungeonRecordTest.cs
DragaliaAPI.Photon.Plugin/DragaliaAPI.Photon.Plugin.csproj
DragaliaAPI.Photon.Plugin/GluonPlugin.Helper.cs
DragaliaAPI.Photon.Plugin/GluonPlugin.cs
DragaliaAPI.Test/Features/TimeAttack/TimeAttackRepositoryTest.cs
DragaliaAPI/Features/Dungeon/Record/DungeonRecordController.cs
DragaliaAPI/Features/TimeAttack/ITimeAttackService.cs
DragaliaAPI/Features/TimeAttack/TimeAttackRepository.cs
DragaliaAPI/Features/TimeAttack/TimeAttackService.cs

On a retry in a co-op room, a time attack record request would be submitted with the same RoomName. The API would think this was the same room name as a previous clear and fail to register it as a new clear, instead attempting to update the units. Fix that by incorporating the room ID -- which is regenerated on retries and clears -- into the unique ID.

Make DbTimeAttackClear key unique for retries

---

DragaliaAPI/Controllers/Dragalia/WebviewVersionController.cs

IsHttps is false because k8s forwards to the backend as http, causing a https redirect leading to opening the system browser

Use https for webviews in production

---

DragaliaAPI.Integration.Test/Dragalia/ToolTest.cs
DragaliaAPI.Integration.Test/HttpClientExtensions.cs
DragaliaAPI.Integration.Test/Other/ExceptionHandlerMiddlewareTest.cs
DragaliaAPI.Photon.Plugin.Test/DragaliaAPI.Photon.Plugin.Test.csproj
DragaliaAPI.Test/Controllers/ToolControllerTest.cs
DragaliaAPI/Controllers/Dragalia/ToolController.cs

For some reason, when sending the `Is-Required-Refresh-Id-Token` error, the client:
- goes back to the BaaS as expected
- changes the `ID-TOKEN` header
- but doesn't change the `id_token` property in the request body??
Maybe the request body property was deprecated internally. Should hopefully fix #115

Use id token from header

---

DragaliaAPI.Integration.Test/Dragalia/PartyTest.cs
DragaliaAPI/Features/PartyPower/PartyPowerService.cs

- Remove AbilityLevel == 0 check, as this is not a valid value -- both exAbilityLevel(s) start at 1

Fix hacked character party power exception

---

DragaliaAPI.Test/Features/Dungeon/DungeonRepositoryTest.cs
DragaliaAPI/Features/Dungeon/DungeonRepository.cs
DragaliaAPI/Features/Fort/FortService.cs
DragaliaAPI/Services/Game/BonusService.cs
DragaliaAPI/Services/Game/LoadService.cs

Currently targeting hot queries that load a lot of data:
- fort bonus list
- /load/index
- building party units for dungeon start / hero param
Could look to disable globally and use AsTracking where needed

Disable change tracking for big queries

---

DragaliaAPI.Test/Features/Dungeon/DungeonRepositoryTest.cs
DragaliaAPI/Features/Dungeon/DungeonRepository.cs
DragaliaAPI/Features/Fort/FortService.cs
DragaliaAPI/Services/Game/BonusService.cs
DragaliaAPI/Services/Game/LoadService.cs

Reverts SapiensAnatis/Dawnshard#444
There have been a bunch of errors in the logs today about players being short of materials which I've never seen before. In other words, the client is out of sync with the backend about what materials it owns.
I'm not quite clear yet on why disabling change tracking might cause this, but it seems the most likely candidate. The only one that seems relevant is LoadService, and that query is after a SaveChangesAsync. Best to revert the changes and investigate the cause before re-applying. Performance benefit was not immediately apparent anyway.

Revert "Disable change tracking for big queries"

---

DragaliaAPI.Integration.Test/Features/QuestBonusTest.cs
DragaliaAPI/Features/Quest/QuestService.cs

When a player skip tickets a quest and claims e.g. 1/3 bonuses, we need to clear the QuestBonusReserveCount, otherwise they will be asked to claim the remaining bonuses when they next login, but the cache entry will be gone.
Also allow the function to return on cache lookup failure, so that a missing cache entry doesn't block players from logging in.
Closes #447

Fix quest cache lookup failure on claiming partial bonus

---

DragaliaAPI.Integration.Test/Features/Missions/MissionTest.cs
DragaliaAPI.Shared/Resources/Missions/MissionProgressionInfo.json
DragaliaAPI/Features/GraphQL/MissionMutations.cs
DragaliaAPI/Features/Missions/MissionInitialProgressionService.cs

- Fix 'Clear High Midgardsormr's Trial: Standard on Solo' counting the co-op version
- Fix 'Upgrade a Wyrmprint's HP & Strength 15 Times' counting augment usage instead of water usage
- Fix 'Obtain Glorious Tempest from the Treasure Trade' not being able to be completed for pre-2.0 saves
- Fix existing GraphQL mutations
- Add new GraphQL 'reset all' mutation when fixes are applied to a particular mission

Royal regimen fixes

---

DragaliaAPI/RazorComponents/News/NewsComponent.razor

OnControlButtonClicked only triggers when pressing the forward/back button and not when clicking a page number. Originally implemented that way to avoid async in a setter, but it seems there's no other way

Trigger scrollup on all paging interaction

---

DragaliaAPI.Test/Services/SessionServiceTest.cs
DragaliaAPI/Features/GraphQL/ImpersionationMutations.cs
DragaliaAPI/Middleware/SessionAuthenticationHandler.cs
DragaliaAPI/Services/Game/SessionService.cs
DragaliaAPI/Services/ISessionService.cs

Allows developers to log in as another user.
Adds GraphQL mutations to set a flag in redis to override the account ID returned from authentication

Add user impersonation

---

.gitignore
DragaliaAPI/Services/Game/SavefileService.cs

- Stop clearing these tables as players became frustrated at losing significant progress when editing their save
- Could consider keeping event compendium tables too

Don't remove kscape or emblems on save import

---

DragaliaAPI.Integration.Test/Dragalia/CharaTest.cs
DragaliaAPI.Integration.Test/Dragalia/DragonTest.cs
DragaliaAPI/Features/Chara/CharaController.cs
DragaliaAPI/Services/Game/DragonService.cs

Mana node unlocks are regularly failing because players already have all the stories of the character they are trying to unlock. This could be due to a save editor bug which has since been fixed. Change this so that it logs a warning instead of throwing; if the story is already unlocked it is probably fine to do nothing even if it shouldn't happen.

Don't throw on chara / dragon story unlock failure

---

DragaliaAPI.Shared/MasterAsset/Models/QuestDrops/QuestDropInfo.cs
DragaliaAPI/Features/Dungeon/QuestEnemyService.cs
DragaliaAPI/Features/Dungeon/SingleValuePicker.cs

FluentRandomPicker throws NotEnoughValuesToPickException when calling .WithPrioritizedElements with a collection that has fewer than 2 values. This is a problem since many boss quests only have 1 enemy. Some quests may only have 1 drop as well.
This commit implements an alternative implementation of IPick<T> that handles the single-element case and create a factory method to handle constructing either FluentRandomPicker's implementation or the custom implementation depending on the array length..

Fix single-enemy quests throwing errors on start

---

DragaliaAPI.Integration.Test/Other/SavefileImportTest.cs
DragaliaAPI/Services/Game/SavefileService.cs

Seems to have been broken in #500 going by the latest save import time in the db, but can't find where this was being done before then either 😲

Fix save import time not updating

---

DragaliaAPI.Shared/MasterAsset/MasterAsset.cs
DragaliaAPI.Shared/MasterAsset/MasterAssetData.cs
DragaliaAPI/Extensions/IEnumerableExtensions.cs
DragaliaAPI/Features/SavefileUpdate/SavefileUpdateService.cs
DragaliaAPI/Features/SavefileUpdate/V14Update.cs

- Preload all emblems in v14update for dupe checking
- Stop story masterassets being loaded on every call
- Add more perf diagnostics around savefile updates

Address some performance issues with savefile updates

---

DragaliaAPI.Integration.Test/Dragalia/AbilityCrestTest.cs
DragaliaAPI.Shared.Test/Unit/MasterAssetTest.cs
DragaliaAPI.Shared/MasterAsset/MasterAssetUtils.cs
DragaliaAPI.Shared/MasterAsset/Models/AbilityCrest.cs
DragaliaAPI.Shared/MasterAsset/Models/AbilityCrestBuildupGroup.cs
DragaliaAPI.Shared/MasterAsset/Models/AbilityCrestBuildupLevel.cs
DragaliaAPI.Shared/MasterAsset/Models/FortPlantDetail.cs
DragaliaAPI.Shared/MasterAsset/Models/WeaponBody.cs
DragaliaAPI.Shared/MasterAsset/Models/WeaponBodyBuildupGroup.cs
DragaliaAPI.Shared/MasterAsset/Models/WeaponBodyBuildupLevel.cs
DragaliaAPI.Shared/MasterAsset/Models/WeaponPassiveAbility.cs
DragaliaAPI.Test/Services/AbilityCrestServiceTest.cs
DragaliaAPI.Test/Services/WeaponServiceTest.cs
DragaliaAPI.Test/UnitTestUtils.cs
DragaliaAPI/Services/Game/AbilityCrestService.cs
DragaliaAPI/Services/Game/WeaponService.cs

Closes #505 and #295 
The root cause of both issues was that certain code in the `AbilityCrestService` was permanently updating a `Dictionary<Materials, int>` material map in instances of `MasterAsset`. These effects would persist until server restart.
@Nightmerp this is 100% my fault for exposing a `Dictionary` publicly rather than the ability crest code
Fix this by using `FrozenDictionary<Materials, int>` instead, and having callers call `ToDictionary` when a copy is needed.

Fix ability crest upgrade issues

---

DragaliaAPI.Database/DatabaseConfiguration.cs
DragaliaAPI.Integration.Test/Other/SavefileImportTest.cs
DragaliaAPI/Services/Game/SavefileService.cs

It turns out that `RemoveRange(IQueryable<TEntity>)` enumerates the query synchronously then tracks all of those as deleted.
We are in a transaction so should be faster and equally as safe to use ExecuteDeleteAsync.

Use ExecuteDeleteAsync over RemoveRange in save import

---

DragaliaAPI.Integration.Test/Dragalia/ToolTest.cs
DragaliaAPI/Services/Game/AuthService.cs

The SaveChanges was throwing because the change tracker had stuff in it which was removed by ExecuteDelete
This highlighted a gap in the save import test coverage, where it was primarily being tested from the dedicated endpoint which is rarely used. So an automated test of a save import from /tool/auth has also been added.

Fix save import error

---

DragaliaAPI.Database/Entities/DbWeaponBody.cs
DragaliaAPI.Database/Migrations/20231204191101_WeaponPassives.Designer.cs
DragaliaAPI.Database/Migrations/20231204191101_WeaponPassives.cs
DragaliaAPI.Database/Repositories/WeaponRepository.cs
DragaliaAPI/AutoMapper/Profiles/UnitReverseMapProfile.cs

- Fix weapon_passive_ability_no_list never getting updated if the duplicate weapon passive ability check is hit. This would mean the passive would always show as able to be unlocked + would always consume materials
- Use an int array for the DB model instead of a formatted string. Uses postgres's int array type. https://learn.microsoft.com/en-us/ef/core/what-is-new/ef-core-8.0/whatsnew#primitive-collections

Weapon passive ability fix + refactoring

---

DragaliaAPI.Test/Features/Fort/FortServiceTest.cs
DragaliaAPI/Features/Fort/FortService.cs

Until now this was based on the buildStartTime, but it should actually be calculated based on the current time.

Fix Wyrmite payment calculation for finishing fort builds

---

DragaliaAPI/Controllers/Dragalia/WebviewVersionController.cs

Set one of the unused webview urls in the app to connect to the photon server to test DNS resolution.

Add photon testing webview

---

DragaliaAPI/Features/Dungeon/QuestEnemyService.cs

A change was made in #527 to order the enemy list by param_id, but it seems other quests strongly dislike this and will start reporting inaccurate information about which enemies were killed, leading to no drops being granted in /dungeon_record/record.

Fix treasure chests not appearing at the end of quests

---

DragaliaAPI.Integration.Test/Features/Event/RaidEventTest.cs
DragaliaAPI/Features/Event/EventRepository.cs
DragaliaAPI/Features/Event/EventService.cs
DragaliaAPI/Features/Event/IEventRepository.cs

A check was implemented in #526 to return null for event user data if the event item dictionary was empty. This was so that the client could be redirected to the appropriate /entry endpoint. However, this would lead to infinite loops of calling /entry when the event was meant to have 0 event items such as Fractured Futures does.
Change the check to be against PlayerEventData which all events are guaranteed to initialize.

Fix event user data always returning null for events with no items

---

DragaliaAPI.Integration.Test/Dragalia/CharaTest.cs
DragaliaAPI/Features/Chara/CharaService.cs

This while loop was checking `playerCharaData.Exp` against the XP required for the character's _current_ level rather than the next one.
This resulted in always levelling up a character even when using 1 crystal.

Fix off-by-one error in levelup calculation

---

.config/dotnet-tools.json
Directory.Packages.props
nuget.config

Leftover from .NET 8 upgrade. Switch off of prerelease Npgsql, code generation, and EF Core design time.

Switch off of RC versions

---

DragaliaAPI.Integration.Test/Features/Dungeon/DungeonRecordTest.cs
DragaliaAPI.Integration.Test/Features/Missions/MissionTest.cs
DragaliaAPI.MissionDesigner/Missions/StarryDragonyule.cs
DragaliaAPI.MissionDesigner/Missions/TollOfTheDeep.cs
DragaliaAPI.MissionDesigner/Models/EventMission/EventPointCollectionMission.cs
DragaliaAPI.MissionDesigner/Models/EventMission/EventPointCollectionRecordMission.cs
DragaliaAPI.MissionDesigner/Models/EventMission/EventRegularBattleClearMission.cs
DragaliaAPI.MissionDesigner/Models/EventMission/EventTrialClearMission.cs
DragaliaAPI.Shared/MasterAsset/Models/Missions/MissionCompleteType.cs
DragaliaAPI.Shared/Resources/Missions/MissionProgressionInfo.json
DragaliaAPI.Test/Features/Dungeon/Record/DungeonRecordRewardServiceTest.cs
DragaliaAPI/Features/Dungeon/Record/DungeonRecordRewardService.cs
DragaliaAPI/Features/Missions/IMissionProgressionService.cs
DragaliaAPI/Features/Missions/MissionProgressionService.cs
DragaliaAPI/Features/Quest/QuestService.cs
DragaliaAPI/Models/DungeonSession.cs

- Don't constrain missions like Clear an Invasion on Expert to a particular quest ID, because we need to detect co-op clears as well. Use the VariationType to check for the difficulty.
- Fix wrong story ID in "Clear all event stories" mission

Fix One Starry Dragonyule endeavour conditions

---

DragaliaAPI.Integration.Test/Features/Missions/MissionTest.cs
DragaliaAPI/Features/Missions/IMissionRepository.cs
DragaliaAPI/Features/Missions/MissionProgressionService.cs
DragaliaAPI/Features/Missions/MissionRepository.cs

There are errors in the logs where people are getting PK exceptions adding to this table. I don't quite understand how that happens, but it's quite a severe issue in terms of blocking people from completing any quests so best to just add some resilience for now.

Add failsafe when adding completed daily missions

---

DragaliaAPI.Photon.Plugin/DragaliaAPI.Photon.Plugin.csproj
DragaliaAPI.Photon.Plugin/GluonPlugin.Helper.cs
DragaliaAPI.Photon.Plugin/GluonPlugin.cs
DragaliaAPI.Photon.Plugin/Helpers/QuestHelper.Data.cs
DragaliaAPI.Photon.Plugin/Helpers/QuestHelper.cs
DragaliaAPI.Photon.Plugin/Models/PluginConfiguration.cs
DragaliaAPI.Photon.Plugin/Models/RoomState.cs
docker-compose.yml

For these quests, players are silently placed in a room behind a loading screen. Photon matchmaking will build up rooms of 1 or more players. Currently these never start; it seems to be on the plugin to trigger the start of the room.
- Detect random matching on room creation.
- If we are in random matching, don't send requests to the Redis API, as these rooms should not be joinable externally.
- If we are in random matching, and a second player joins, set a timer after which the game will start. The duration is configurable in the plugin config.
- If the timer is started, and a player leaves such that there is now only one player in the room, abort the timer.

Add support for random matching quests to plugin

---

DragaliaAPI.Integration.Test/Features/SavefileUpdate/ISavefileUpdateTest.cs
DragaliaAPI.Integration.Test/Features/SavefileUpdate/SavefileUpdateTestFixture.cs
DragaliaAPI.Integration.Test/Features/SavefileUpdate/V16UpdateTest.cs
DragaliaAPI/Features/Event/EventDataExtensions.cs
DragaliaAPI/Features/Event/EventService.cs
DragaliaAPI/Features/SavefileUpdate/V16Update.cs

When creating event items, we do a .Zip() of the IDs from `<type>EventItem` from the MasterAsset into `Enum.GetValues<{Type}EventItemType>()`. 
However, it appears that `data.GetEventSpecificItemIds()` is not guaranteed to be returned in order, leading to situations like this:
Here, the Id and Type columns are out of sync, leading to event points being rewarded as gold event items and event points never getting saved.
This PR changes the `.GetEventSpecificItemIds()` to return the corresponding item type, since it is defined in the same MasterAsset entry.
I could equally have just added sorting to the returned event item IDs but using the type defined in the same MasterAsset entry feels like the safest approach.

Fix event item IDs sometimes not matching the item type

---

DragaliaAPI.Integration.Test/Features/SavefileUpdate/ISavefileUpdateTest.cs
DragaliaAPI.Integration.Test/Features/SavefileUpdate/V17UpdateTest.cs
DragaliaAPI/Features/PartyPower/PartyPowerService.cs
DragaliaAPI/Features/SavefileUpdate/V17Update.cs

- Add a savefile update that detects missing dragon reliability entries and adds them
- Remove throw condition in party power calculation when reliability is missing; `GetDragonPower` is able to handle `reliability` being null, and if this throws on missing reliability during `V11Update` then `V17Update` will never be reached.

Add missing dragon reliability save update

---

DragaliaAPI.Integration.Test/Features/Dungeon/AutoRepeatTest.cs
DragaliaAPI.Integration.Test/Features/Dungeon/DungeonRecordTest.cs
DragaliaAPI.Integration.Test/Features/Dungeon/DungeonStartTest.cs
DragaliaAPI.Shared/Definitions/Enums/Dungeon/RepeatSettingType.cs
DragaliaAPI/Controllers/Dragalia/MypageController.cs
DragaliaAPI/Extensions/DistributedCacheExtensions.cs
DragaliaAPI/Extensions/EnumerableExtensions.cs
DragaliaAPI/Features/Dungeon/AutoRepeat/AutoRepeatService.cs
DragaliaAPI/Features/Dungeon/AutoRepeat/IAutoRepeatService.cs
DragaliaAPI/Features/Dungeon/AutoRepeat/RepeatController.cs
DragaliaAPI/Features/Dungeon/AutoRepeat/RepeatInfo.cs
DragaliaAPI/Features/Dungeon/Extensions.cs
DragaliaAPI/Features/Dungeon/IDungeonStartService.cs
DragaliaAPI/Features/Dungeon/Record/DungeonRecordController.cs
DragaliaAPI/Features/Dungeon/Record/DungeonRecordService.cs
DragaliaAPI/Features/Dungeon/Skip/DungeonSkipController.cs
DragaliaAPI/Features/Dungeon/Start/DungeonStartController.cs
DragaliaAPI/Features/Dungeon/Start/DungeonStartService.cs
DragaliaAPI/Models/Generated/Components.cs
DragaliaAPI/Models/Generated/Requests.cs
DragaliaAPI/Models/Options/RedisOptions.cs
DragaliaAPI/ServiceConfiguration.cs
DragaliaAPI/appsettings.json

- Add redis caching of `repeat_setting` from start requests, and send this back on record requests when `repeat_setting` is 1
- Add `repeat/end` endpoint
- Send repeat data on `mypage/info` requests when the auto-repeat was interrupted.
Note: the client implements automatic stamina consumption itself through automatic calls to `item/use_recovery_stamina`, so no work is needed for this on the backend.

Add auto-repeat

---

DragaliaAPI.MissionDesigner/Missions/V1Missions.cs
DragaliaAPI.Shared/Resources/Missions/MissionProgressionInfo.json

The total value of the EventGroupCleared mission is always 1, so this mission was impossible to complete if the initial progress handler did not complete it for you.
It's debatable whether 'Clear 2 Void Battles' means clear 2 _different_ void battles. I have interpreted it in the same way as the 'Clear Five Quests' daily endeavour which is to make it so 2 clears of the same quest count.

Don't use total value for Clear 2 Void Battles mission

---

DragaliaAPI.Integration.Test/Dragalia/DragonTest.cs
DragaliaAPI.Integration.Test/Features/Fort/FortTest.cs
DragaliaAPI.Integration.Test/Features/Missions/MissionTest.cs
DragaliaAPI.Test/Features/Fort/FortControllerTest.cs
DragaliaAPI.Test/Features/Login/ResetHelperTest.cs
DragaliaAPI.Test/Services/DragonServiceTest.cs
DragaliaAPI/Features/Fort/FortController.cs
DragaliaAPI/Helpers/IResetHelper.cs
DragaliaAPI/Helpers/ResetHelper.cs
DragaliaAPI/Services/Game/DragonService.cs
DragaliaAPI/Services/IDragonService.cs

- Make the rotating gift use the last reset's DayOfWeek so that it
changes at reset rather than 12AM UTC
- Stop the ! notification icon from always appearing on the dragon's
roost button by correctly sending free_gift_count. This is based on
whether the Fresh Bread gift is available
- Update `LastContactTime` when gifting a dragon so that the 
'Recently Gifted' menu functions correctly
- Refactor ResetHelper to use TimeProvider rather than IDateTimeProvider

Dragon's Roost gifting fixes

---

DragaliaAPI.Integration.Test/Other/SavefileImportTest.cs
DragaliaAPI/Services/Game/SavefileService.cs

Importing a save would previously delete all dragon gifts, leading to the returned list from /dragon/get_contact_data being empty until the next reset where gifts could be replenished.

Fix dummy dragon gifts appearing after save import

---

DragaliaAPI.Integration.Test/Features/Dungeon/DungeonRecordTest.cs
DragaliaAPI.Test/Features/Dungeon/Record/DungeonRecordRewardServiceTest.cs
DragaliaAPI.Test/Features/Dungeon/Record/DungeonRecordServiceTest.cs
DragaliaAPI/Features/Dungeon/Record/DungeonRecordRewardService.cs
DragaliaAPI/Features/Dungeon/Record/DungeonRecordService.cs
DragaliaAPI/Features/Dungeon/Record/IDungeonRecordRewardService.cs
DragaliaAPI/Features/Quest/IQuestService.cs
DragaliaAPI/Features/Quest/QuestService.cs

Quest bonuses are never received because the `isFirstClear` check will always return false, because `ProcessQuestMissionCompletion` is called after `ProcessQuestCompletion` in `DungeonRecordService` and so the quest entity will always have been marked as completed before this check is reached.
- Swap the order of the calls (removed unused `DbQuest` return of `ProcessQuestCompletion` as a result)
- Change the check to examine the `State` property instead of play count to not include failed attempts / make consistent with other checks
- Add a test for first clear rewards

Fix quest first clear bonuses

---

DragaliaAPI.Integration.Test/Features/Dungeon/DungeonRecordTest.cs
DragaliaAPI.Shared/MasterAsset/Models/QuestRewards/QuestScoreMissionData.cs
DragaliaAPI.Test/Services/DragonServiceTest.cs
DragaliaAPI/Features/Dungeon/IQuestCompletionService.cs
DragaliaAPI/Features/Dungeon/QuestCompletionService.cs
DragaliaAPI/Features/Reward/Handlers/FafnirMedalRewardHandler.cs

Onslaught events e.g. Twinkling Twilight don't use the wave as the index into their `QuestScoreMissionData`; they instead only have one value set. However, they share `EventKindType.Combat` with defensive events, which _do_ use the wave.
Implement a slightly hacky conditional statement when looking up the base score to handle the case where the array has only one non-zero value, which should be returned instead of indexing.
Also add a stub reward handler for fafnir medals; fixes server error popups when receiving these (which you are sometimes forced to when claiming combat event rewards).

Fix onslaught events not granting any glory

---

.github/workflows/lint.yaml
.github/workflows/publish-push.yaml
.github/workflows/test.yaml

I'm going to delete the `master` branch and rename `develop` to `main`.
We don't get a lot of use out of `master` because we don't do stable releases -- we have done in the past but these have never been deployed, and were more for the benefit of versioning the photon plugin / state manager.

Configure workflows to run on main

---

DragaliaAPI.MissionDesigner/Missions/PermanentDailies.cs
DragaliaAPI.MissionDesigner/Missions/StarryDragonyule.cs
DragaliaAPI.MissionDesigner/Missions/TollOfTheDeep.cs
DragaliaAPI.MissionDesigner/Models/Attributes/ContainsMissionListAttribute.cs
DragaliaAPI.MissionDesigner/Models/Attributes/EventIdAttribute.cs
DragaliaAPI.MissionDesigner/Models/Attributes/ImplicitPropertyAttribute.cs
DragaliaAPI.MissionDesigner/Models/Attributes/MissionListAttribute.cs
DragaliaAPI.MissionDesigner/Models/Attributes/MissionTypeAttribute.cs
DragaliaAPI.MissionDesigner/Models/EventMission/EarnEnemiesKilledMission.cs
DragaliaAPI.MissionDesigner/Models/EventMission/EventChallengeBattleClearMission.cs
DragaliaAPI.MissionDesigner/Models/EventMission/EventParticipationMission.cs
DragaliaAPI.MissionDesigner/Models/EventMission/EventPointCollectionMission.cs
DragaliaAPI.MissionDesigner/Models/EventMission/EventPointCollectionRecordMission.cs
DragaliaAPI.MissionDesigner/Models/EventMission/EventQuestClearWithCrestMission.cs
DragaliaAPI.MissionDesigner/Models/EventMission/EventRegularBattleClearMission.cs
DragaliaAPI.MissionDesigner/Models/EventMission/EventTrialClearMission.cs
DragaliaAPI.MissionDesigner/Program.cs
DragaliaAPI.MissionDesigner/ReflectionHelper.cs

Adds `ImplicitPropertyAttribute`, which is a generic version of the way that `MissionListAttribute` sets the type for all missions in a list. This is used to additionally set the `EventId` for all missions in event lists.
If a property is attempted to be set which does not exist (for example a generic clear quest mission in an event mission list), it is skipped and a message is logged.
There are no changes to `MissionProgressionInfo.json` with this update.

Add ImplicitPropertyAttribute to MissionDesigner

---

DragaliaAPI.Integration.Test/Features/Missions/MissionTest.cs
DragaliaAPI/Features/Missions/IMissionRepository.cs
DragaliaAPI/Features/Missions/MissionRepository.cs
DragaliaAPI/Features/Missions/MissionService.cs

If you return a mission whose `end_date` is in the past, the game will repeatedly refresh the mission window on the assumption the data is stale.
Also includes misc. refactoring of some mission code

Don't return out of date missions from /mission/get_mission_list

---

Directory.Packages.props
DragaliaAPI.Photon.Plugin/DragaliaAPI.Photon.Plugin.csproj
DragaliaAPI.Photon.Shared/DragaliaAPI.Photon.Shared.csproj
docker-compose.yml

- Unify MessagePack version in solution (tested plugin still works)
- Stop using prereleases for Serilog.Sinks.File, FluentAssertions, and Microsoft.NET.Test.Sdk
- Add compose profile for statemanager as a better alternative to commenting out the service

Switch off of prerelease versions

---

DragaliaAPI.Integration.Test/Features/SavefileUpdate/V14UpdateTest.cs
DragaliaAPI/Features/SavefileUpdate/V14Update.cs

Prevent V14Update from adding an earned character story epithet if V10Update has already added it due to the player having it equipped.
Closes #539

Fix V14Update and V10Update conflict

---

DragaliaAPI.Integration.Test/Features/Dungeon/DungeonRecordTest.cs
DragaliaAPI.Integration.Test/Features/Dungeon/DungeonStartTest.cs
DragaliaAPI/Features/Dungeon/Record/DungeonRecordService.cs
DragaliaAPI/Features/Dungeon/Start/DungeonStartService.cs
DragaliaAPI/Services/Game/TutorialService.cs
DragaliaAPI/Services/ITutorialService.cs

- Fix co-op tutorial using your units instead of the bots, by setting `is_bot_tutorial` to true when it is in progress
- Fix co-op tutorial infinitely repeating by advancing tutorial status on record

Fix co-op tutorial

---

DragaliaAPI.Integration.Test/Features/SavefileUpdate/V18UpdateTest.cs
DragaliaAPI/Features/Missions/IMissionRepository.cs
DragaliaAPI/Features/Missions/MissionRepository.cs
DragaliaAPI/Features/SavefileUpdate/V18Update.cs

.AnyAsync() doesn't return true if the mission is tracked but not yet saved, apparently

Fix change tracker conflict with V15 and V18 updates

---

PhotonPlugin/DragaliaAPI.Photon.Plugin.Test/DragaliaAPI.Photon.Plugin.Test.csproj
PhotonPlugin/DragaliaAPI.Photon.Plugin/DragaliaAPI.Photon.Plugin.csproj
Shared/DragaliaAPI.Photon.Shared/DragaliaAPI.Photon.Shared.csproj
Shared/DragaliaAPI.Photon.Shared/Models/ApiGame.cs

Remove extra unneeded packages from shared project, which almost halves the number of assemblies included with the plugin build.
Had to retarget the photon plugin due to the following error: `CSC: Error CS1705 : Assembly 'MessagePack' with identity 'MessagePack, Version=2.5.0.0, Culture=neutral, PublicKeyToken=b4a0369545f0a1be' uses 'System.Memory, Version=4.0.1.2, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' which has a higher version than referenced assembly 'System.Memory' with identity 'System.Memory, Version=4.0.1.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'`
Most likely S.T.J reference was upgrading the project somehow? But not sure. Re-adding that fixes the issue, but we don't want to keep it.
Still appears to work fine on net 4.7.2, plugin is loaded and breakpoints …

Remove extra references indirect references from photon plugin

---

DragaliaAPI/DragaliaAPI/Features/Dungeon/Record/DungeonRecordService.cs
DragaliaAPI/DragaliaAPI/Models/Generated/Components.cs
DragaliaAPI/DragaliaAPI/Models/Generated/IngameResultData.cs

This was being done before #676, and with it removed and placed in a service, we started seeing NullReferenceExceptions in /dungeon_record/record.
Let's try reverting it back to exactly how it was before...

Default-initialize reward record and grow record

---

DragaliaAPI/DragaliaAPI/Models/Generated/Components.cs

`Pickup` was being incorrectly serialized as an integer

Fix "Problem with received data" error on tutorial summon

---

DragaliaAPI/DragaliaAPI.Integration.Test/Dragalia/SummonTest.cs
DragaliaAPI/DragaliaAPI/Features/Summoning/SummonController.cs

This is currently blocking summoning with payment target errors, but the way the data is currently being stored isn't quite right. If we disabled the payment target, the next error would be material shortage since we store each ticket with its own key ID and don't delete them when the quantity reaches 0.
Needs a rethink - so for now disable sending tickets so that people can still summon with wyrmite.

Stop sending summon ticket info

---

DragaliaAPI/DragaliaAPI/Models/Generated/EventTradeGetListResponse.cs
DragaliaAPI/DragaliaAPI/Models/Generated/EventTradeTradeResponse.cs
DragaliaAPI/DragaliaAPI/Models/Generated/Requests.cs
DragaliaAPI/DragaliaAPI/Models/Generated/Responses.cs

Cause appears to be a previously always-null `material_list` property in two of the event trade responses, which with #676 was now being default initialized to an empty list, causing the game to think its material inventory is empty.

Fix material item list removing all items

---

DragaliaAPI/DragaliaAPI.Integration.Test/CustomWebApplicationFactory.cs
DragaliaAPI/DragaliaAPI.Integration.Test/Features/DmodeDungeon/DmodeDungeonTest.cs
DragaliaAPI/DragaliaAPI.Integration.Test/TestFixture.cs
DragaliaAPI/DragaliaAPI/Features/DmodeDungeon/DmodeDungeonService.cs

Closes #485. Adds an exception handler to the finish endpoint to still
return a response if no Redis data is found, allowing bugged runs to
be abandoned so that the Kaleidoscape can still be accessed

Allow abandoning Kaleidoscape run if redis data retrieval fails

---

DragaliaAPI/DragaliaAPI.Integration.Test/Features/Dungeon/AutoRepeatTest.cs
DragaliaAPI/DragaliaAPI/Features/Dungeon/AutoRepeat/AutoRepeatService.cs

This appears to be caused by the client sending a stale repeat key, instead of null, if you auto repeat a quest and then auto repeat another quest after ending the first auto repeat.
Change the handling so that when we receive a repeat key which is invalid, we act in the same way as if we had received null on a first clear, and go to the viewer ID lookup.

Fix "invalid repeat key" warning spam

---

DragaliaAPI/DragaliaAPI.Database/Entities/DbPlayer.cs
DragaliaAPI/DragaliaAPI.Integration.Test/Dragalia/WeaponBodyTest.cs
DragaliaAPI/DragaliaAPI/Mapping/Mapperly/CharaMapper.cs
DragaliaAPI/DragaliaAPI/Mapping/Mapperly/PartyMapper.cs
DragaliaAPI/DragaliaAPI/Mapping/Mapperly/WeaponBodyMapper.cs
DragaliaAPI/DragaliaAPI/Models/Generated/Components.cs
DragaliaAPI/DragaliaAPI/Models/Generated/UserData.cs
DragaliaAPI/DragaliaAPI/Models/Generated/WeaponBodyList.cs
DragaliaAPI/DragaliaAPI/Services/Game/LoadService.cs
DragaliaAPI/DragaliaAPI/Services/Game/SavefileService.cs
DragaliaAPI/DragaliaAPI/Services/ISavefileService.cs

Use mapperly to generate an expression tree which will allow us to select fewer columns from the DB in `/load/index`.
Warmed up performance seems about the same (~50ms)  as deployment, but furthers our goal to switch away from AutoMapper anyway

Use mapperly for /load/index

---

DragaliaAPI/DragaliaAPI.Integration.Test/Other/SavefileImportTest.cs
DragaliaAPI/DragaliaAPI/Services/Game/SavefileService.cs

Prevents an issue where attempting to claim a historical daily endeavour after a save import will throw a server error, since the corresponding mission row is missing

Delete daily mission data on save import

---

.github/workflows/test-report.yaml
Directory.Packages.props
DragaliaAPI/DragaliaAPI.Database.Test/packages.lock.json
DragaliaAPI/DragaliaAPI.Database/ApiContext.cs
DragaliaAPI/DragaliaAPI.Database/Repositories/IInventoryRepository.cs
DragaliaAPI/DragaliaAPI.Database/Repositories/InventoryRepository.cs
DragaliaAPI/DragaliaAPI.Database/packages.lock.json
DragaliaAPI/DragaliaAPI.Integration.Test/DragaliaAPI.Integration.Test.csproj
DragaliaAPI/DragaliaAPI.Integration.Test/Features/Login/LoginTest.cs
DragaliaAPI/DragaliaAPI.Integration.Test/Features/Present/PresentTest.cs
DragaliaAPI/DragaliaAPI.Integration.Test/TestFixture.cs
DragaliaAPI/DragaliaAPI.Integration.Test/packages.lock.json
DragaliaAPI/DragaliaAPI.Test.Utils/packages.lock.json
DragaliaAPI/DragaliaAPI.Test/Features/Login/LoginControllerTest.cs
DragaliaAPI/DragaliaAPI.Test/Services/DragonServiceTest.cs
DragaliaAPI/DragaliaAPI.Test/packages.lock.json
DragaliaAPI/DragaliaAPI/Features/Login/DragonGiftResetAction.cs
DragaliaAPI/DragaliaAPI/Features/Login/LoginController.cs
DragaliaAPI/DragaliaAPI/Features/Reward/Handlers/DragonGiftHandler.cs
DragaliaAPI/DragaliaAPI/Services/Game/DragonService.cs
DragaliaAPI/DragaliaAPI/packages.lock.json

On daily reset:
- Only grant today's rotating gift
- Clear expired rotating gifts
In general:
- Remove repo methods in favour of global query filters

Fix dragon gift reset

---

DragaliaAPI/DragaliaAPI.Integration.Test/Features/Login/LoginTest.cs
DragaliaAPI/DragaliaAPI/Features/Login/DragonGiftResetAction.cs

Golden chalice appears twice in the rotating gift list, so we must continually update the dict as we go along

Fix change tracker error with rotating gifts

---

DragaliaAPI/DragaliaAPI.Integration.Test/Features/Login/LoginTest.cs
DragaliaAPI/DragaliaAPI/Features/Login/DragonGiftResetAction.cs

New dragon gift reset algorithm in #728 will wipe the golden chalice on Saturdays because it sees that it's also Sundays gift

Fix golden chalice

---

DragaliaAPI/DragaliaAPI.Database/Entities/DbPlayer.cs
DragaliaAPI/DragaliaAPI.Integration.Test/Dragalia/WeaponBodyTest.cs
DragaliaAPI/DragaliaAPI/Mapping/Mapperly/CharaMapper.cs
DragaliaAPI/DragaliaAPI/Mapping/Mapperly/PartyMapper.cs
DragaliaAPI/DragaliaAPI/Mapping/Mapperly/WeaponBodyMapper.cs
DragaliaAPI/DragaliaAPI/Models/Generated/Components.cs
DragaliaAPI/DragaliaAPI/Models/Generated/UserData.cs
DragaliaAPI/DragaliaAPI/Models/Generated/WeaponBodyList.cs
DragaliaAPI/DragaliaAPI/Services/Game/LoadService.cs
DragaliaAPI/DragaliaAPI/Services/Game/SavefileService.cs
DragaliaAPI/DragaliaAPI/Services/ISavefileService.cs

This was merged in #714 but reverted because people were being kicked to the tutorial en masse. I think the issue was a missing `Where` in LoadService when accessing the players table :roll_eyes: Would explain why this worked fine in a test environment.

Use mapperly for /load/index re-attempt

---

Directory.Packages.props
DragaliaAPI/DragaliaAPI.Integration.Test/Features/Load/LoadIndexTest.cs
DragaliaAPI/DragaliaAPI/Services/Game/LoadService.cs

#744 appears to have introduced a regression where party units are not sorted when returned from /load/index, leading to players seeing strange "Your party data has been updated" messages.
Have upgraded to a prerelease mapperly as it allows us to inline the sorting as part of the db query. See https://next.mapperly.riok.app/docs/configuration/queryable-projections/#user-implemented-mapping-methods

Sort units in parties from /load/index

---

DragaliaAPI/DragaliaAPI.Integration.Test/Dragalia/DragonTest.cs
DragaliaAPI/DragaliaAPI/Services/Game/DragonService.cs

Fix a softlock when reaching bond level 5 or 15 in the Dragon's Roost. We were creating an array of size 1 but early returning if the bond level unlocked a story. This lead to returning a list of `[null]`, which the game didn't like. This PR changes that to return an empty list `[]` in this case.
It also makes it so that the reward.IsReleaseStory flag is set even if the story fails to unlock due to invalid savedata. This is because if you send `[]` without `IsReleaseStory` then it shows an empty gifts screen, which is a minor visual glitch.

Fix dragon's roost gifting softlock

---

DragaliaAPI/DragaliaAPI.Database.Test/Repositories/WeaponRepositoryTest.cs
DragaliaAPI/DragaliaAPI.Database/Repositories/IWeaponRepository.cs
DragaliaAPI/DragaliaAPI.Database/Repositories/WeaponRepository.cs
DragaliaAPI/DragaliaAPI.Integration.Test/Features/Dungeon/DungeonStartTest.cs
DragaliaAPI/DragaliaAPI/Features/Dungeon/Start/DungeonStartService.cs
DragaliaAPI/DragaliaAPI/Services/Photon/HeroParamService.cs

The current logic to retrieve weapon passive abilities uses the equipped weapon's element, when it should use the character's element. This manifests as not having any passive abilities active if you use an off-element weapon, because the off-element passive abilities won't apply correctly. The actual behaviour should be that a weapon passive that has been unlocked is active for all units of that element and weapon type, regardless of what weapon is being used.
Additionally removes if statements that only send weapon passive data if a weapon is equipped. Weapon passive abilities should be available even when no weapon is equipped.

Fix weapon passives not applying when using off-element weapons

---

DragaliaAPI/DragaliaAPI.Integration.Test/Features/Missions/MissionTest.cs
DragaliaAPI/DragaliaAPI/Features/GraphQL/MutationBase.cs
DragaliaAPI/DragaliaAPI/Features/Missions/MissionService.cs

A player got into a state where they were unable to progress the main campaign as their client was refusing to call `/mission/unlock_main_story_group`. Upon further investigation it seems the cause of this is that we are always sending
`current_main_story_mission` from `/mission/get_mission_list` with data, even if it relates to main story missions that are already completed.
This lead to the missions showing as completed on their screen, but without any endeavours to claim and with the quest remaining locked.
Fix this by filtering out the current main story mission to those that are not claimed. We will therefore send an empty
`current_main_story_mission` if none is in progress. This fixes the issue, and lines up with what I have seen in my captures from my main account on the official …

Fix story mission softlock

---

DragaliaAPI/DragaliaAPI.Database/Entities/Scaffold/DbDetailedPartyUnit.cs
DragaliaAPI/DragaliaAPI/Features/Dungeon/Start/DungeonStartService.Log.cs
DragaliaAPI/DragaliaAPI/Features/Dungeon/Start/DungeonStartService.cs
DragaliaAPI/DragaliaAPI/Features/SavefileUpdate/V20Update.cs
DragaliaAPI/DragaliaAPI/Services/Photon/HeroParamService.cs

I've observed the following exception in the logs since https://github.com/SapiensAnatis/Dawnshard/pull/752 was merged:
```
System.NullReferenceException: Object reference not set to an instance of an object.
at DragaliaAPI.Features.Dungeon.Start.DungeonStartService.ProcessDetailedUnitList(List`1 detailedPartyUnits) in /src/DragaliaAPI/DragaliaAPI/Features/Dungeon/Start/DungeonStartService.cs:line 292
at DragaliaAPI.Features.Dungeon.Start.DungeonStartService.GetAssignUnitIngameData(Int32 questId, IList`1 party, Nullable`1 supportViewerId, RepeatSetting repeatSetting) in /src/DragaliaAPI/DragaliaAPI/Features/Dungeon/Start/DungeonStartService.cs:line 151
at DragaliaAPI.Features.Dungeon.Start.DungeonStartController.StartAssignUnit(DungeonStartStartAssignUnitRequest request, CancellationToken …
```

Maybe fix NullReferenceException in party loading code 

---

DragaliaAPI/DragaliaAPI.Integration.Test/Features/Login/LoginTest.cs
DragaliaAPI/DragaliaAPI.Test/Features/Login/ResetHelperTest.cs
DragaliaAPI/DragaliaAPI/Features/Login/DragonGiftResetAction.cs
DragaliaAPI/DragaliaAPI/Services/Game/DragonService.Log.cs
DragaliaAPI/DragaliaAPI/Services/Game/DragonService.cs

Attempting to track down an issue where the rotating gift is changing over 1h early each day. Can't work it out from the code so hoping some debug logs might help.
Code inspection turned up a bug in DragonGiftResetAction where we might use the next day's gift if you experience daily reset at e.g. 2AM UTC.

Add additional logging around rotating gifts

---

.config/dotnet-tools.json
DragaliaAPI/DragaliaAPI.Database/ApiContextFactory.cs
DragaliaAPI/DragaliaAPI.Database/DatabaseConfiguration.cs
DragaliaAPI/DragaliaAPI.Database/DragaliaAPI.Database.csproj
DragaliaAPI/DragaliaAPI.Database/Entities/DbAbilityCrestSet.cs
DragaliaAPI/DragaliaAPI.Database/Entities/DbDeviceAccount.cs
DragaliaAPI/DragaliaAPI.Database/Entities/DbNewsItem.cs
DragaliaAPI/DragaliaAPI.Database/Entities/DbPartyUnit.cs
DragaliaAPI/DragaliaAPI.Database/Entities/DbSetUnit.cs
DragaliaAPI/DragaliaAPI.Database/Entities/DbTimeAttackClear.cs
DragaliaAPI/DragaliaAPI.Database/Entities/DbTimeAttackClearUnit.cs
DragaliaAPI/DragaliaAPI.Database/Entities/DbTimeAttackPlayer.cs
DragaliaAPI/DragaliaAPI.Database/Entities/DbWeaponBody.cs
DragaliaAPI/DragaliaAPI.Database/Migrations/20240419230507_StringLength.Designer.cs
DragaliaAPI/DragaliaAPI.Database/Migrations/20240419230507_StringLength.cs
DragaliaAPI/DragaliaAPI.Database/PostgresOptions.cs
DragaliaAPI/DragaliaAPI/RazorComponents/TimeAttack/OwnClear.razor

- Limit string length of columns to potentially improve performance
- Add design time factory to be able to configure migrations (migrations broken since Design package was removed from main API project in #746) cc @Nightmerp 
To configure a migration now:
- from the repo root do `dotnet ef migrations add MyMigration -p DragaliaAPI/DragaliaAPI.Database -s DragaliaAPI/DragaliaAPI.Database`
- cd to `DragaliaAPI/DragaliaAPI.Database` and just do `dotnet ef migrations add MyMigration`
If you want to use `dotnet ef database update`, the context factory accepts config from the CLI or env variables in the same format as docker-compose `PostgresOptions__*` but I haven't tried this

EFCore tweaks

---

DragaliaAPI/DragaliaAPI.Integration.Test/Features/Present/PresentTest.cs
DragaliaAPI/DragaliaAPI.Integration.Test/Features/Summoning/SummonTest.cs
DragaliaAPI/DragaliaAPI/Features/Reward/Handlers/SummonTicketHandler.cs

Fixes an issue where two summon ticket rows could be added if you claimed two presents with summon tickets simultaneously, as subsequent invocations of SummonTicketHandler weren't aware of the pending row in the change tracker.
Additionally bump time tolerance due to summon history test failures in CI

Fix duplicate summon ticket rows

---

DragaliaAPI/DragaliaAPI/App.razor
DragaliaAPI/DragaliaAPI/Pages/News/NewsWebview.razor
DragaliaAPI/DragaliaAPI/RazorComponents/Cookies.cs
DragaliaAPI/DragaliaAPI/RazorComponents/MainLayout.razor
DragaliaAPI/DragaliaAPI/RazorComponents/News/NewsComponent.razor
DragaliaAPI/DragaliaAPI/RazorComponents/Routes.razor
DragaliaAPI/DragaliaAPI/RazorComponents/WebviewLayout.razor

Adds an icon and a border around news posts that are new based on
a local storage item that is set by the page indicating when it was last visited.
Also:
- Move loading of news items from OnInitializedAsync to
OnAfterRenderAsync. The former is called twice and causes a flicker,
as well as a wasteful DB query.
- Remove FocusOnNavigate that focused the title element on each page
- Some minor refactoring of the cookie logic, from when I thought I
would use cookies to store the last date

Add indicator to fresh news posts

---

DragaliaAPI/DragaliaAPI.Integration.Test/Features/Trade/TreasureTradeTest.cs
DragaliaAPI/DragaliaAPI/Features/Present/IPresentService.cs
DragaliaAPI/DragaliaAPI/Features/Present/PresentService.cs
DragaliaAPI/DragaliaAPI/Features/Reward/Handlers/DragonHandler.cs
DragaliaAPI/DragaliaAPI/Features/Reward/IRewardService.cs
DragaliaAPI/DragaliaAPI/Features/Reward/RewardService.cs
DragaliaAPI/DragaliaAPI/Features/Summoning/SummonService.cs
DragaliaAPI/DragaliaAPI/Features/Summoning/UnitService.cs
DragaliaAPI/DragaliaAPI/Features/Trade/ITradeService.cs
DragaliaAPI/DragaliaAPI/Features/Trade/TradeService.cs
DragaliaAPI/DragaliaAPI/Features/Trade/TreasureTradeController.cs

More fallout from #792 - I forgot that you can trade for multiple dragons at once in treasure trade. After #792 this only gives 1 dragon and scams the player, as DragonHandler ignores `Entity.Quantity`. This is actually quite tricky to handle since each dragon could put you over the limit.
This change special-cases dragon trades and splits them up to be sent to the batch reward handler one-by-one which can process each one individually. To accomplish this the BatchGrantReward method has been expanded to use a fallback for non-batchable entities instead of just throwing.

Fix DragonHandler ignoring multiple dragons

---

DragaliaAPI/DragaliaAPI/Services/Game/LoadService.cs

This was performing the wrong check and would show a notification if there _wasn't_ an item summon available, compared to the check in /mypage/info.
Closes #762

Fix shop exclamation mark reappearing

---

DragaliaAPI/DragaliaAPI.Shared/Resources/Missions/MainStoryMissionGroupRewards.json
DragaliaAPI/DragaliaAPI/Services/Game/BonusService.cs

Closes #766
It is not actually possible to have the game not show this pop-up, even if you send the list as `null`, so I dug a bit deeper and it turns out that there are rewards meant to be shown here. Source is Gigz's entire campaign recording:
https://youtu.be/S4V_Luy-ZnY?t=977
Screencap:
Implement these rewards + some fixes to BonusService I needed to enable cheats while testing

Fix empty Ch 13 endeavour reward list

---

.github/workflows/build.yaml
DragaliaAPI/DragaliaAPI/Dockerfile
PhotonStateManager/DragaliaAPI.Photon.StateManager/Dockerfile

- Use non-root user
- Remove custom image argument, as dependabot doesn't understand it *1
- Remove redunant CI arg *2
*1 This was previously done to avoid using chiseled images locally as doing so caused the VS container debugging to die after not finding `tail`. This has been fixed in 17.10 Preview 2 and should be released soon https://github.com/microsoft/DockerTools/issues/409 
*2 This was done to not generate MissionProgressionInfo in CI but this condition was removed from the project file in #746

Update image builds

---

PhotonPlugin/DragaliaAPI.Photon.Plugin/DragaliaAPI.Photon.Plugin.csproj
PhotonPlugin/DragaliaAPI.Photon.Plugin/Plugins/GameLogic/GameLogicPlugin.cs
PhotonPlugin/DragaliaAPI.Photon.Plugin/Plugins/Gluon/GluonPlugin.cs
PhotonPlugin/DragaliaAPI.Photon.Plugin/Shared/PluginStateService.cs

The practice of not publishing StateManager events when a room's ShouldPublish flag is false is probably incorrect, since it breaks the ability to join private rooms via passcode if no room is ever created in Redis.
In general, it is probably best to update StateManager in all cases even if not _strictly_ necessary, for example updating player count in random matching rooms. The requests are generally non-blocking and will not cause any user-facing announcements. So we should limit the publish restrictions to the Discord plugin which does make user-facing announcements.

Publish statemanager events for private rooms

---

DragaliaAPI/DragaliaAPI.Integration.Test/Features/Quest/QuestReadStoryTest.cs
DragaliaAPI/DragaliaAPI/Features/Story/StoryService.cs

The edge case fix in #800 for having full storage when trying to complete the story that gives you Midgardsormr has its own edge case. It causes a PK error if you somehow already have Midgardsormr - which is possible via save editing.

Handle Midgardsormr reliability PK error in fallback

---

DragaliaAPI/DragaliaAPI/Program.cs

Accidentally replaced with /api routing as part of #835. Whoopsie!

Add website back into routing

---

DragaliaAPI/DragaliaAPI/Features/Event/EventDropService.cs
DragaliaAPI/DragaliaAPI/Properties/launchSettings.json

Closes #507
Replaces the calculation based on VariationType with one that looks at the least significant digits of the quest ID, as these always follow a particular structure for wave quests across all events. It produces an identical result to the old calculation assuming that the old calculation was intended for typical events with VariationType 3 and 4 in the wave quests.
\+ `launchSettings.json` fix for making the server accessible via a mobile device

Fix T3 event materials being unavailable from certain events

---

DragaliaAPI/DragaliaAPI/RazorComponents/News/NewsComponent.razor

The MG news item was added as part of #850 but was filtered from the Svelte site, however it is now showing on the Blazor website

Filter out hidden news items in Blazor

---

DragaliaAPI/DragaliaAPI.Integration.Test/Features/Summoning/SummonTest.cs
DragaliaAPI/DragaliaAPI/Features/Summoning/FeatureExtensions.cs
DragaliaAPI/DragaliaAPI/Features/Summoning/SummonBannerOptions.cs
DragaliaAPI/DragaliaAPI/Features/Summoning/SummonController.cs
DragaliaAPI/DragaliaAPI/Features/Summoning/SummonOddsService.cs
DragaliaAPI/DragaliaAPI/Features/Summoning/SummonService.Log.cs
DragaliaAPI/DragaliaAPI/Features/Summoning/SummonService.cs
DragaliaAPI/DragaliaAPI/appsettings.Testing.json

Closes #698.
Second half of work started in #849, which only implemented the calculation. This PR implements the logic to accumulate the pity counter when summoning, as well as the "maximum pity" mechanic which guarantees a five-star after reaching 9% pity rate.

Add pity rate accumulation

---

DragaliaAPI/DragaliaAPI.Integration.Test/Features/Dungeon/AutoRepeatTest.cs
DragaliaAPI/DragaliaAPI/Controllers/Dragalia/MypageController.cs
DragaliaAPI/DragaliaAPI/Features/Dungeon/AutoRepeat/AutoRepeatService.cs
DragaliaAPI/DragaliaAPI/Features/Dungeon/AutoRepeat/RepeatController.cs

Closes #764.
We need to set `RepeatData` to null in the `/repeat/end` response, to convince the client that auto-repeat is over.
One would have thought it was smart enough to realize that calling `/repeat/end` means that auto-repeat has ended. :shrug:

Fix auto-repeat counter not resetting

---

DragaliaAPI/DragaliaAPI/Middleware/MaintenanceActionFilter.cs
DragaliaAPI/DragaliaAPI/Middleware/ResourceVersionActionFilter.cs

Change action filters to run after requests have been processed

---

DragaliaAPI/DragaliaAPI.Integration.Test/Features/Dungeon/DungeonRecordTest.cs
DragaliaAPI/DragaliaAPI.Integration.Test/Features/Summoning/SummonTest.cs
DragaliaAPI/DragaliaAPI.Integration.Test/Features/Wall/WallRecordTest.cs
DragaliaAPI/DragaliaAPI.Integration.Test/Features/Wall/WallTest.cs
DragaliaAPI/DragaliaAPI.Integration.Test/TestFixture.cs
DragaliaAPI/DragaliaAPI.Shared/Definitions/Enums/VariationTypes.cs
DragaliaAPI/DragaliaAPI.Test/Controllers/DungeonControllerTest.cs
DragaliaAPI/DragaliaAPI.Test/Features/Dungeon/DungeonServiceTest.cs
DragaliaAPI/DragaliaAPI.Test/Features/Wall/WallRecordControllerTest.cs
DragaliaAPI/DragaliaAPI/Extensions/DistributedCacheExtensions.cs
DragaliaAPI/DragaliaAPI/Features/Dungeon/DungeonController.cs
DragaliaAPI/DragaliaAPI/Features/Dungeon/DungeonMapper.cs
DragaliaAPI/DragaliaAPI/Features/Dungeon/DungeonService.cs
DragaliaAPI/DragaliaAPI/Features/Dungeon/DungeonSession.cs
DragaliaAPI/DragaliaAPI/Features/Dungeon/IDungeonService.cs
DragaliaAPI/DragaliaAPI/Features/Dungeon/IDungeonStartService.cs
DragaliaAPI/DragaliaAPI/Features/Dungeon/Record/DungeonRecordController.cs
DragaliaAPI/DragaliaAPI/Features/Dungeon/Start/DungeonStartController.cs
DragaliaAPI/DragaliaAPI/Features/Dungeon/Start/DungeonStartService.cs
DragaliaAPI/DragaliaAPI/Features/Quest/IQuestService.cs
DragaliaAPI/DragaliaAPI/Features/Quest/QuestService.cs
DragaliaAPI/DragaliaAPI/Features/Wall/WallController.cs
DragaliaAPI/DragaliaAPI/Features/Wall/WallRecordController.cs
DragaliaAPI/DragaliaAPI/Features/Wall/WallStartController.cs
DragaliaAPI/DragaliaAPI/Models/DungeonSession.cs

~~Speculative fix for random auto-repeat glitches throwing up stale data, and something we should be doing anyway.~~
Today, when you finish a dungeon, the session remains in the cache for the remainder of its expiry time, because issues were previously encountered with the client retrying record requests if they take too long, and then encountering errors because the session had been deleted on the first request.
Now that the codebase makes better use of CancellationToken, this is much less likely if we put the eviction of the session right at the end of the response method. It is still possible if the request is cancelled during serialization, however. If we encounter issues we can make the RemoveDungeon method instead mark the session to be removed in 1 minute's time or similar.
Also …

Actually remove dungeon sessions

---

.env.default
DragaliaAPI/DragaliaAPI.Integration.Test/Features/Dungeon/DungeonRecordTest.cs
DragaliaAPI/DragaliaAPI/Middleware/PhotonAuthenticationHandler.cs
DragaliaAPI/DragaliaAPI/Models/Options/PhotonOptions.cs
DragaliaAPI/DragaliaAPI/Program.cs
DragaliaAPI/DragaliaAPI/ServiceConfiguration.cs
DragaliaAPI/DragaliaAPI/appsettings.Testing.json
PhotonPlugin/README.md
PhotonStateManager/DragaliaAPI.Photon.StateManager.Test/CustomWebApplicationFactory.cs
PhotonStateManager/DragaliaAPI.Photon.StateManager.Test/TestFixture.cs
PhotonStateManager/DragaliaAPI.Photon.StateManager/Authentication/PhotonAuthenticationHandler.cs
PhotonStateManager/DragaliaAPI.Photon.StateManager/Models/PhotonOptions.cs
PhotonStateManager/DragaliaAPI.Photon.StateManager/Program.cs
PhotonStateManager/README.md

- Adds support for the [key-per-file](https://learn.microsoft.com/en-us/dotnet/core/extensions/configuration-providers#key-per-file-configuration-provider) configuration provider to the app.
- Also fixes the lambda for adding `IPhotonStateApi` to make it pull an updated value for the base URL.
- Miscellaneous refactoring to PhotonStateManager config, including better use of DI and `IConfiguratioon`.
This includes several breaking changes for PhotonStateManager:
- `PHOTON_TOKEN` environment variable -> `PhotonOptions__Token`
- `ENABLE_HTTPS` environment variable no longer used, consult ASP.NET docs for alternative
---
This is primarily intended to solve the issue of the API having to re-template and restart each time the state manager is deployed, due to the fact that Nomad selects a …

Update PhotonStateManager related configuration

---

DragaliaAPI/DragaliaAPI/ServiceConfiguration.cs

I was operating under the mistaken assumption that `IOptions<T>` represented the config value at the time of injection and that you only needed `IOptionsMonitor<T>` if you expected the value to change while you were holding on to the instance...
Turns out `IOptions<T>` does not reload at all at runtime.

Use IOptionsMonitor to hot reload config

---

DragaliaAPI/DragaliaAPI/Controllers/DragaliaControllerBase.cs
DragaliaAPI/DragaliaAPI/Features/Summoning/RedoableSummonController.cs
DragaliaAPI/DragaliaAPI/Infrastructure/DragaliaHttpConstants.cs
DragaliaAPI/DragaliaAPI/Middleware/ExceptionHandlerMiddleware.cs
DragaliaAPI/DragaliaAPI/Middleware/LogContextMiddleware.cs
DragaliaAPI/DragaliaAPI/Middleware/SessionAuthenticationHandler.cs
DragaliaAPI/DragaliaAPI/Program.cs
DragaliaAPI/DragaliaAPI/ServiceConfiguration.cs
DragaliaAPI/DragaliaAPI/appsettings.json

Adding this header to the log context to prove a hypothesis about repeated unsafe requests, in which the client retries requests that mutate server state, for example clearing a dungeon or finishing an upgrade
If the request token header is the same for these we may be able to use output caching to serve up a cached response. I will investigate errors like the above and see if I can prove that the Request-Token remains the same
Contributes towards #875

Add Request-Token header to log context

---

.github/workflows/lint.yaml
.github/workflows/test-api.yaml
.github/workflows/test-statemanager.yaml
DragaliaAPI.sln

Prompted by the recent dependabot config update to target the other components... GH actions is free but I don't want to abuse their genorosity and ruin the climate :)
- Only run csharpier for dotnet tool upgrades and cs file changes
- Use same `changes` rules for running test pipelines on main as are applied to pull requests.

Make workflows more specific to changed files

---

DragaliaAPI/DragaliaAPI.Database.Test/Repositories/FortRepositoryTest.cs
DragaliaAPI/DragaliaAPI.Database/ApiContext.cs
DragaliaAPI/DragaliaAPI.Database/Repositories/QuestRepository.cs
DragaliaAPI/DragaliaAPI.Integration.Test/Features/StorySkip/StorySkipTest.cs
DragaliaAPI/DragaliaAPI.Integration.Test/Other/GlobalQueryFilterTest.cs
DragaliaAPI/DragaliaAPI/Features/Fort/FortRepository.cs
DragaliaAPI/DragaliaAPI/Features/StorySkip/StorySkipController.cs
DragaliaAPI/DragaliaAPI/Features/StorySkip/StorySkipService.cs
DragaliaAPI/DragaliaAPI/Features/Wall/WallService.cs

Seeing errors in the logs about people attempting to access Mercurial Gauntlet without the required DbQuestWalls initialized. It seems the gap here is story skip - you skip past the MG story but without having the data initialized. Attempting to read the story after this will not send a request to the server.
Will need to run a DB query after this to fix affected saves.
Plus a usual bunch of misc refactoring and global query filter usage.

Initialize Mercurial Gauntlet on story skip

---

PhotonPlugin/DragaliaAPI.Photon.Plugin/DragaliaAPI.Photon.Plugin.csproj
PhotonPlugin/DragaliaAPI.Photon.Plugin/Plugins/Discord/DiscordPlugin.cs
PhotonPlugin/DragaliaAPI.Photon.Plugin/Plugins/StateManager/StateManagerPlugin.cs
PhotonPlugin/DragaliaAPI.Photon.Plugin/Properties/launchSettings.json

There are some errors in the logs where the OnCloseGame callback of the StateManagerPlugin is failing because there is no RoomId property.
This appears to happen if a player joins a game and it closes instantly, typically due to connection issues. It seems in this case the code in OnCreateGame which would initialize the RoomId does not have a chance to run.
These headers are not required for the state manager or for Zena, and are only used for recording time attack clears in the main API (for requests originating from GameLogicPlugin). So the simplest thing to do is remove them.

Fix failure to get RoomId in OnCloseGame callback

---

DragaliaAPI/DragaliaAPI/Features/Web/Savefile/SavefileController.cs
DragaliaAPI/DragaliaAPI/Features/Web/WebAuthenticationHelper.cs
DragaliaAPI/DragaliaAPI/Services/Api/BaasApi.cs
DragaliaAPI/DragaliaAPI/Services/Api/IBaasApi.cs
Website/.env
Website/.env.development
Website/src/hooks.server.ts
Website/src/routes/(main)/account/+layout.ts
Website/src/routes/(main)/account/profile/+page.ts
Website/src/routes/(main)/account/profile/saveExport.svelte
Website/src/routes/(main)/news/[pageNo=integer]/+page.ts
Website/src/routes/(main)/news/news.ts
Website/src/routes/(main)/oauth/+page.server.ts
Website/src/routes/webview/news/[pageNo=integer]/+page.ts
Website/src/routes/webview/news/detail/[id=integer]/+page.ts
Website/vite.config.ts

think the cause of the 404 is upon us... the JWT subject from the SDK token is a web account ID, we need a game account ID (which was already being done in the existing auth, I just forgot about it)
also:
- implement caching in WebAuthenticationHelper
- fix SavefileController route
- remove static PUBLIC_DAWNSHARD_API_URL and always use the current page origin to form api urls, for better compatibility with samesite cookies

Misc website fixes

---

Website/src/hooks.server.ts

Fixes 401s when SSRing the profile page after the request is rewritten

Forward JWT cookie as header

---

DragaliaAPI/DragaliaAPI/Features/Web/Savefile/SavefileController.cs

- Return wrapped response with data property
- Change Content-Type; I've observed my iPhone to default saving the file as savedata.txt.json and wonder if changing the Content-Type could fix that to save it as just .txt

Fix website save export

---

DragaliaAPI/DragaliaAPI/Models/Generated/Components.cs
DragaliaAPI/DragaliaAPI/Models/Generated/DungeonRecordRecordMultiRequest.cs
DragaliaAPI/DragaliaAPI/Models/Generated/Requests.cs
PhotonPlugin/DragaliaAPI.Photon.Plugin/DragaliaAPI.Photon.Plugin.csproj
PhotonPlugin/DragaliaAPI.Photon.Plugin/Plugins/GameLogic/GameLogicPlugin.cs
PhotonPlugin/DragaliaAPI.Photon.Plugin/Plugins/GameLogic/GoToIngameStateManager.cs
PhotonPlugin/DragaliaAPI.Photon.Plugin/Plugins/GameLogic/RoomState.cs
PhotonPlugin/DragaliaAPI.Photon.Plugin/Plugins/Gluon/GluonPlugin.cs
PhotonPlugin/DragaliaAPI.Photon.Plugin/Plugins/Gluon/GluonPluginFactory.cs
PhotonPlugin/DragaliaAPI.Photon.Plugin/Shared/Constants/ActorPropertyKeys.cs
PhotonPlugin/DragaliaAPI.Photon.Plugin/Shared/Helpers/DtoHelpers.cs

Closes #799, #667
- Adds the following top-level properties to the `/dungeon_record/record_multi` by inserting these when the request is proxied by the Photon server.:
- `astral_bet_count`: The astral raid multiplier chosen by the current player when starting the quest.
- `connecting_viewer_id_list`: The list of viewer IDs all other players in the co-op room.
- `member_count`: The number of units, including AI units, that the current player used in the quest.
- `is_host`: Whether the current player was the host of the quest. Obsoletes PhotonStateManager endpoint.
- Fixes Discord plugin not respecting disable setting; if it is not enabled the sub-plugin is set to null.
Example new request for a room in which two players played together with 1 AI unit each:
```json
{ …
```

Augment requests to /dungeon_record/record_multi

---

DragaliaAPI/DragaliaAPI.Integration.Test/Features/Dungeon/DungeonRecordTest.cs
DragaliaAPI/DragaliaAPI/Features/Dungeon/Record/DungeonRecordController.cs
DragaliaAPI/DragaliaAPI/Features/Dungeon/Record/DungeonRecordHelperService.cs
DragaliaAPI/DragaliaAPI/Features/Dungeon/Record/IDungeonRecordHelperService.cs
DragaliaAPI/DragaliaAPI/Models/Generated/DungeonRecordRecordMultiRequest.cs
DragaliaAPI/DragaliaAPI/Models/Generated/Requests.cs
DragaliaAPI/DragaliaAPI/Services/Photon/IMatchingService.cs
DragaliaAPI/DragaliaAPI/Services/Photon/MatchingService.cs
PhotonPlugin/DragaliaAPI.Photon.Plugin/DragaliaAPI.Photon.Plugin.csproj
PhotonPlugin/DragaliaAPI.Photon.Plugin/Plugins/GameLogic/GameLogicPlugin.cs
PhotonStateManager/DragaliaAPI.Photon.StateManager.Test/Event/EntryConditionsTest.cs
PhotonStateManager/DragaliaAPI.Photon.StateManager.Test/Event/GameCloseTest.cs
PhotonStateManager/DragaliaAPI.Photon.StateManager.Test/Event/GameCreateTest.cs
PhotonStateManager/DragaliaAPI.Photon.StateManager.Test/Event/GameJoinTest.cs
PhotonStateManager/DragaliaAPI.Photon.StateManager.Test/Event/GameLeaveTest.cs
PhotonStateManager/DragaliaAPI.Photon.StateManager.Test/Event/MatchingTypeTest.cs
PhotonStateManager/DragaliaAPI.Photon.StateManager.Test/Event/RoomIdTest.cs
PhotonStateManager/DragaliaAPI.Photon.StateManager.Test/Event/VisibleTest.cs
PhotonStateManager/DragaliaAPI.Photon.StateManager.Test/Get/ByViewerIdTest.cs
PhotonStateManager/DragaliaAPI.Photon.StateManager.Test/Get/GameListTest.cs
PhotonStateManager/DragaliaAPI.Photon.StateManager.Test/Get/IsHostTest.cs
PhotonStateManager/DragaliaAPI.Photon.StateManager/Controllers/EventController.cs
PhotonStateManager/DragaliaAPI.Photon.StateManager/Controllers/GetController.cs
PhotonStateManager/DragaliaAPI.Photon.StateManager/Models/RedisGame.cs
PhotonStateManager/DragaliaAPI.Photon.StateManager/Models/RedisPlayer.cs

- Use ConnectingViewerIdList to save an API call on record
- Make /Get/ByViewerId /Get/IsHost more efficient by only retrieving one
game
Might fix #385 as the new list should be ordered by actor number but we will see

Optimize dungeon record using new photon server properties

---

DragaliaAPI/DragaliaAPI.Database/Entities/DbPlayerCharaData.cs
DragaliaAPI/DragaliaAPI/Features/StorySkip/StorySkipService.cs

This should be true for all characters except those that are temporary and whose event has ended, judging by the endgame savefile.
It does not make any difference at the minute since we don't support temporary adventurers, but the save editor complains about it

Default chara.list_view_flag to true

---

DragaliaAPI/DragaliaAPI.Integration.Test/Dragalia/PartyTest.cs
DragaliaAPI/DragaliaAPI.Integration.Test/Dragalia/ToolTest.cs
DragaliaAPI/DragaliaAPI.Integration.Test/Other/ExceptionHandlerMiddlewareTest.cs
DragaliaAPI/DragaliaAPI/Controllers/DragaliaControllerBase.cs
DragaliaAPI/DragaliaAPI/Features/Web/Savefile/SavefileController.cs
DragaliaAPI/DragaliaAPI/Infrastructure/Middleware/MaintenanceActionFilter.cs
DragaliaAPI/DragaliaAPI/Infrastructure/Middleware/NotFoundHandlerMiddleware.cs
DragaliaAPI/DragaliaAPI/Infrastructure/Middleware/ResourceVersionActionFilter.cs
DragaliaAPI/DragaliaAPI/Infrastructure/Middleware/SetResultCodeActionFilter.cs
DragaliaAPI/DragaliaAPI/Models/Results/DragaliaResponse.cs
DragaliaAPI/DragaliaAPI/ServiceConfiguration.cs

Modern controllers tend to return a `TData` directly, by having a signature of `DragaliaResult<TData>` which returns an `IActionResult` by implementing `IConvertToActionResult`. This bypasses the mechanism implemented in #1016 inside `DragaliaControllerBase` which sets the `ResultCode` based on the use of `Ok()` or `Code()`.
To have the result code set in these cases, use an action filter that runs after all actions and attempts to determine if the result is a `DragaliaResponse` and, if it is, extract the result code. I've had to implement an abstract class for this as it wouldn't be possible to pass a value for the generic argument.
This mechanism replaces any need to set the result code manually in `DragaliaControllerBase`.
Also changed the constructors of `DragaliaResponse` to make …

FIx result code being logged as null if returning an object directly

---

.github/workflows/build-manual.yaml
.github/workflows/build.yaml
.github/workflows/deploy.yaml
.github/workflows/integration-test.yaml
.github/workflows/publish-api.yaml
.github/workflows/publish-statemanager.yaml
.github/workflows/test.yaml
Directory.Packages.props
DragaliaAPI.sln
DragaliaAPI/Directory.Build.props
DragaliaAPI/version.json
PhotonStateManager/Directory.Build.props
PhotonStateManager/version.json

Implements [NerdBank.GitVersioning](https://github.com/dotnet/nerdbank.gitversioning) to derive tags.
This will allow us to maintain immutable image tags rather than just re-tagging `:latest` repeatedly, which should help with version immutability and allow me to remove some hacks that make Nomad force re-pull the image on job resubmission.

Implement NerdBank.GitVersioning

---

DragaliaAPI/DragaliaAPI.Integration.Test/Other/OutputCachingTest.cs
DragaliaAPI/DragaliaAPI.Integration.Test/TestFixture.cs
DragaliaAPI/DragaliaAPI/Infrastructure/DragaliaHttpConstants.cs
DragaliaAPI/DragaliaAPI/Infrastructure/OutputCaching/RepeatedRequestPolicy.cs

Incoming /dungeon_record/record_multi requests were being subjected to output caching after #1016, because the Photon server does not set Request-Token or SID so the vary-by headers were always the same. This lead to P2 being served P1's response which lead to a softlock.
Fix this by only caching requests where a Request-Token was present in the first place. This also replaces the existing workaround to disable output caching in the automated tests.

Fix co-op softlock for player 2

---

DragaliaAPI/DragaliaAPI/Features/Summoning/SummonService.cs

Resolves EF core warning: `The query uses a row limiting operator ('Skip'/'Take') without an 'OrderBy' operator. This may lead to unpredictable results.`

Fix lack of ordering on summon history query

---

DragaliaAPI/DragaliaAPI.Test/Features/Fort/FortServiceTest.cs
DragaliaAPI/DragaliaAPI/Features/Fort/FortService.cs

The cost of the final smithywyrm has always been incorrect at 750. The wiki confirms it is 700. This has started to cause errors in the logs about failed payments now that diamantium is available and wyrmite is limited.

Fix smithywyrm cost

---

Website/src/routes/health/+server.ts

We don't want the website to return an Internal Error page for the healthcheck if the fetch fails to get a response

Add try/catch to website healthcheck

---

DragaliaAPI/DragaliaAPI/Features/Present/PresentControllerService.cs

On testing the save editor I was hitting a fail point I added when attempting to grant multiple dragons without using the batch handler.
https://github.com/SapiensAnatis/Dawnshard/blob/8f25035986ee218d3b9b024b61e42f4323323a14/DragaliaAPI/DragaliaAPI/Features/Reward/Handlers/DragonHandler.cs#L17-L25
We need to use the batch handler for presents to ensure all types of presents can be claimed - I suspect multiple dragons in one present was not possible before the editor.

Use batch reward handler to claim presents

---

DragaliaAPI/DragaliaAPI/Features/Present/PresentControllerService.cs

Needed to prevent duplicate characters added by the editor remaining in your gift box forever

Remove discarded presents from box

---

DragaliaAPI/DragaliaAPI/Services/Api/BaasApi.cs

These are spamming the error logs when it's an expected case if someone logs into the website (calling /api/user/me) with a BaaS account that doesn't have a dawnshard device account linked

Don't log errors for user ID not found

---

DragaliaAPI/DragaliaAPI/Infrastructure/OutputCaching/RepeatedRequestPolicy.cs

Prevents unauthenticated requests becoming cached for all users. The Request-Token is not as random as we thought. It is calculated by
`(CurrentRequestId + 1) & 0xFFFFFF | (UnixTime(DateTime.UtcNow) << 24)`
which could mean that two clients making a series of unauthenticated requests at the same time could receive the same token, i.e. it is not actually pseudo- random as originally assumed.

Don't cache requests without a SID header

---

DragaliaAPI/DragaliaAPI.Database/ApiContext.cs
DragaliaAPI/DragaliaAPI.Integration.Test/Features/Present/PresentTest.cs
DragaliaAPI/DragaliaAPI.Integration.Test/Other/GlobalQueryFilterTest.cs
DragaliaAPI/DragaliaAPI/Extensions/ServiceCollectionExtensions.cs
DragaliaAPI/DragaliaAPI/Features/Dmode/DmodeRepository.cs
DragaliaAPI/DragaliaAPI/Features/Reward/Handlers/DmodePointRewardHandler.cs
DragaliaAPI/DragaliaAPI/Features/Reward/Handlers/GenericRewardHandler.cs
DragaliaAPI/DragaliaAPI/Features/Reward/Handlers/IBatchRewardHandler.cs
DragaliaAPI/DragaliaAPI/Features/Reward/RewardService.cs

Currently the server throws an error if you try and claim a present orother reward containing Kaleidoscape amber before unlocking the Kaleidoscape mode. This is because it can't find the DbPlayerDmodeInfo
to update.
This was never really a problem until the introduction of the save editor, where people seem to be quite commonly hitting this case.
Introduce a reward handler for these which can initialize the Kaleidoscape data when attempting to claim a present.
It seems that having any kaleidoscape data initialized will then lead the game to skip the kaleidoscape intro (and calling /dmode/entry) so there shouldn't be any PK conflicts.

Fix server error when claiming amber before initializing kaleidoscape

---

DragaliaAPI/DragaliaAPI/Features/Web/Savefile/SavefileEditService.cs
Website/src/routes/(main)/account/save-editor/present/presentWidget.svelte

Some players have run into an issue where particulary quantities of items e.g. 2,147,483,647 diamantium are not claimable
999,999 is the maximum hustle hammers which is the lowest of all entity types that currently have defined limits. It should be enough for most editing operations, if not it's trivial to just add more presents.

Adjust max present quantity in save editor down

---

DragaliaAPI/DragaliaAPI.Integration.Test/Dragalia/UserTest.cs
DragaliaAPI/DragaliaAPI.Test/Helpers/BaasRequestHelperTest.cs
DragaliaAPI/DragaliaAPI/Controllers/Dragalia/UserController.cs
DragaliaAPI/DragaliaAPI/Program.cs
DragaliaAPI/DragaliaAPI/ServiceConfiguration.cs
DragaliaAPI/DragaliaAPI/Services/Api/BaasApi.cs
DragaliaAPI/DragaliaAPI/Services/Api/IBaasApi.cs

Uses a new API on the BaaS to retrieve the username of the linked account, and shows this in the 'Account Management' menu.
This will assist in troubleshooting issues with account linking where people cannot log into the website and are getting the 404 error.

Show BaaS username in account management dialog

---

DragaliaAPI/DragaliaAPI.Integration.Test/Features/Dungeon/DungeonRecordTest.cs
DragaliaAPI/DragaliaAPI.Integration.Test/Features/Dungeon/DungeonSkipTest.cs
DragaliaAPI/DragaliaAPI.Shared/MasterAsset/Models/QuestRewards/QuestRewardData.cs
DragaliaAPI/DragaliaAPI.Test/Features/Dungeon/Record/DungeonRecordRewardServiceTest.cs
DragaliaAPI/DragaliaAPI.Test/Features/Dungeon/Record/DungeonRecordServiceTest.cs
DragaliaAPI/DragaliaAPI/Features/Dungeon/DungeonSession.cs
DragaliaAPI/DragaliaAPI/Features/Dungeon/IQuestEnemyService.cs
DragaliaAPI/DragaliaAPI/Features/Dungeon/QuestEnemyService.cs
DragaliaAPI/DragaliaAPI/Features/Dungeon/Record/DungeonRecordRewardService.cs
DragaliaAPI/DragaliaAPI/Features/Dungeon/Record/DungeonRecordService.cs
DragaliaAPI/DragaliaAPI/Features/Dungeon/Record/IDungeonRecordRewardService.cs
DragaliaAPI/DragaliaAPI/Features/Dungeon/Skip/DungeonSkipController.cs
DragaliaAPI/DragaliaAPI/Features/Present/Present.cs
DragaliaAPI/DragaliaAPI/Models/Generated/Components.cs
DragaliaAPI/DragaliaAPI/Models/Generated/OddsInfo.cs

Add drops of draconic essences to hard / very hard main story quests.
The visual indicator of the number of essence available is driven by `quest_list[].daily_play_count`, which we already handle correctly in `QuestService.ProcessQuestCompletion`. So the only change that needs to be made is checking whether the quest drops essence, and whether our play count is low enough, and then granting it.

Add draconic essence drops

---

Website/src/routes/(main)/headerContents.svelte
Website/src/routes/(main)/login/+page.server.ts

The cause of the login issues appears to be Chrome specifically re-generating the challenge string when it visits /oauth, causing it to not match the hash we sent to BaaS.

Re-use challengeString cookie if it is already set

---

DragaliaAPI/DragaliaAPI/Features/Reward/RewardService.cs
DragaliaAPI/DragaliaAPI/Models/Generated/AtgenDropAll.cs
DragaliaAPI/DragaliaAPI/Models/Generated/Components.cs

This is the start of the work to replace the existing 50-of-everything drop tables with hand-picked values.
For these drops I've used the clears helpfully uploaded here https://www.youtube.com/watch?v=PBA7tQtd5Kw as a reference, with some fudging to round numbers since we are supplying averages.
Also a minor visual fix for every drop having a 'New!' adornment on the drops screen

Update Imperial Onslaught quest drops

---

DragaliaAPI/DragaliaAPI/Controllers/DragaliaControllerBase.cs
DragaliaAPI/DragaliaAPI/Controllers/SerializeExceptionAttribute.cs
DragaliaAPI/DragaliaAPI/Infrastructure/Middleware/ExceptionHandlerMiddleware.cs
DragaliaAPI/DragaliaAPI/Program.cs

After adding metrics, our 'unhandled exception' counter never increases, probably because we handle all exceptions in ExceptionHandlerMiddleware
Put the exception handler middleware as a dedicated exception handler rather than just a generic middleware with try/catch to ensure ASP.NET increments the unhandled exception counter

Refactor exception handler middleware

---

DragaliaAPI/DragaliaAPI.Integration.Test/Features/Tool/ToolTest.cs
DragaliaAPI/DragaliaAPI/Controllers/Dragalia/TransitionController.cs
DragaliaAPI/DragaliaAPI/Controllers/DragaliaControllerBase.cs
DragaliaAPI/DragaliaAPI/Features/Tool/ToolController.cs
DragaliaAPI/DragaliaAPI/Features/Web/FeatureExtensions.cs
DragaliaAPI/DragaliaAPI/Features/Web/Users/UserController.cs
DragaliaAPI/DragaliaAPI/Infrastructure/Authentication/AuthConstants.cs
DragaliaAPI/DragaliaAPI/ServiceConfiguration.cs

After #1135 I noticed from the logs that SessionAuthentication runs when accessing `/tool/auth`, `/tool/reauth`, `/tool/signup`, etc.
This allows you to access the controller with a valid session ID but invalid token, which causes `DoLogin` to crash on failing to retrieve the subject, as you have no JWT identity.
Fix this by removing the implicit SessionAuthentication from DragaliaControllerBaseCore.

Prevent access to /tool/auth with valid session ID and invalid token

---

DragaliaAPI/DragaliaAPI.Test/Features/Fort/FortServiceTest.cs
DragaliaAPI/DragaliaAPI/Features/Fort/FortService.cs

Investigating as part of #436.
Adds some debug logging to indicate the state of the fort at the time these exceptions get thrown.

Add debug logging to fort error cases

---

DragaliaAPI/DragaliaAPI.Database.Test/DragaliaAPI.Database.Test.csproj
DragaliaAPI/DragaliaAPI.Database.Test/Repositories/FortRepositoryTest.cs
DragaliaAPI/DragaliaAPI.Integration.Test/Features/Fort/FortTest.cs
DragaliaAPI/DragaliaAPI/Features/Fort/FortRepository.cs

Contributes to #436. Changes the used carpenter count calculation to be based on the number of buildings currently under construction which aren't finished, rather than any building that has a non-zero BuildEndDate.
This is because if you start an upgrade that takes e.g. 10 seconds, we report you have 3/4 builders. That's fine. But 10 seconds later, when the client sees that build complete using its internal timer, it then believes 4/4 builders are available, but we currently would say it's still 3/4 until you actually call levelup_end by tapping the building. I believe this desync is what causes the FortBuildCarpenterBusy exception.

Exclude completed buildings from working_carpenter_num

---

DragaliaAPI/DragaliaAPI/Services/Game/SavefileService.cs

- Don't delete WallRewardDates on import to stop the first /login/index call failing, if the savefile update is not run first
- Don't trust the viewer ID of the mapped user data from the input savefile

Savefile import fixes

---

DragaliaAPI/DragaliaAPI.Integration.Test/Features/Story/StorySkipTest.cs
DragaliaAPI/DragaliaAPI.Test/Features/Wall/WallControllerTest.cs
DragaliaAPI/DragaliaAPI/Features/Login/LoginService.cs
DragaliaAPI/DragaliaAPI/Features/Login/SavefileUpdate/V21Update.cs
DragaliaAPI/DragaliaAPI/Features/Wall/IWallService.cs
DragaliaAPI/DragaliaAPI/Features/Wall/WallController.cs
DragaliaAPI/DragaliaAPI/Features/Wall/WallService.cs

After I made WallRewardDate entities hang around between save imports in #1186, it became possible to hit a case where unlocking Mercurial Gauntlet through gameplay would attempt to add another row to the table and fail on a primary key error.
This would occur, I assume, if you imported a save that had unlocked MG and then re-imported a fresh save that hadn't, and attempted to unlock it again.
Fix this by changing the initialization method to also lazily initialize WallRewardDates, as it already does for the wall level entities.

Fix duplicate key errors on WallRewardDate table

---

PhotonPlugin/DragaliaAPI.Photon.Plugin/Plugins/GameLogic/GoToIngameStateManager.cs
Shared/DragaliaAPI.Photon.Shared/Models/ActorInfo.cs

Needed for Orchis to determine if it should send event boost information without doing a race-condition-prone lookup in its own session records as to the current quest ID for the given user.

Send quest ID with hero param request

---

.github/workflows/integration-test.yaml
.github/workflows/test-api.yaml
.github/workflows/test.yaml
DragaliaAPI/Directory.Build.props
DragaliaAPI/DragaliaAPI.MasterAssetConverter/DragaliaAPI.MasterAssetConverter.csproj
DragaliaAPI/DragaliaAPI.MasterAssetConverter/MasterAssetConverter.targets
DragaliaAPI/DragaliaAPI.MissionDesigner/DragaliaAPI.MissionDesigner.csproj
DragaliaAPI/DragaliaAPI.MissionDesigner/MissionDesigner.targets
DragaliaAPI/DragaliaAPI/Dockerfile
DragaliaAPI/DragaliaAPI/DragaliaAPI.csproj
PhotonStateManager/DragaliaAPI.Photon.StateManager/Dockerfile

Updates the automated generation of mission progression info and msgpack master asset files to leverage MSBuild a bit better:
- Use actual project references instead of manual builds. Allows removing random restore steps from Dockerfiles/CI
- Split the targets into their own files to clean up DragaliaAPI.csproj
- Use FileWrites instead of manually deleting files on clean

Update MSBuild automation

---

DragaliaAPI/DragaliaAPI.Test/Features/Wall/WallTimeProviderExtensionsTests.cs
DragaliaAPI/DragaliaAPI/Features/Wall/WallTimeProviderExtensions.cs

Happy New Year!
Players are being greeted today by a server error when calling `/login/index` because we are trying to create a `DateTimeOffset` with a date of `15/0/2024` as the last MG reward date.
This code was written this year and failed to account for the January edge case where subtracting 1 from the month is not valid.

Fix Mercurial Gauntlet reward check January error

---

.github/workflows/build.yaml

Might fix some issues we've been having where builds are almost completely un-cached

Add scope to Docker image builds

---

DragaliaAPI/DragaliaAPI.Integration.Test/Features/Story/StorySkipTest.cs
DragaliaAPI/DragaliaAPI/Features/Story/Skip/StorySkipService.cs
DragaliaAPI/DragaliaAPI/Features/Wall/WallService.cs

- Ensure we add dragon reliability for dragons added during story skip. Otherwise players will encounter server errors when interacting with new dragons in the roost.
- Ensure we add the first episode of character stories for characters added during story skip.
- Fix InitializeWall not being idempotent and causing a PK conflict in the PlayerMissions table if the player has already unlocked MG prior to doing a story skip.

Story skip fixes

---

PhotonStateManager/DragaliaAPI.Photon.StateManager/PhotonStateManagerMetrics.cs

The room count data currently shows up like this:
But there are no keys in the Redis database for those rooms.
I think this is because Prometheus scrapes when there are open rooms, and then when these rooms are removed, simply returning a single measurement of 0 doesn't overwrite the more specific room measurements we returned earlier.
Fix this by making the metric dumber and always returning two measurements (for public/private) which may or may not be 0.

Fix room count metric

---

DragaliaAPI/DragaliaAPI/Infrastructure/Middleware/ResultCodeLoggingMiddleware.cs

Avoid logging a result code error when someone inputs an invalid room ID

Don't log an error for room not found

---

Website/src/routes/csp/+server.ts
Website/svelte.config.js

Adding `object-src: none` and `base-uri: none` as per the guidance of https://csp-evaluator.withgoogle.com/
Note that SvelteKit does not support unsafe-inline fallbacks; we would need to add `strict-dynamic` which is officially unsupported at the minute. Adding `unsafe-inline` also removes the nonce and breaks the entire page as the browser ignores it due to the unsafe-hashes workaround, but the missing nonce means no other scripts can execute.
`require-trusted-types` also is apparently not supported.

Expand CSP policy

---

Website/src/routes/(main)/(home)/+page.svelte

iOS users entering a server URL require a trailing slash due to limitations of the modded IPA. Android is indifferent towards trailing slash or no slash. The website URL should have a trailing slash to ensure iOS users aren't left with broken apps.

Fix website URL on main page

---

Website/src/routes/csp/+server.ts

We're getting a lot of CSP violation reports that I am unable to reproduce. The `unsafe-hashes` part of the CSP is only supported by CSP Level 3 browsers, so I'm wondering if the reports are coming from old browsers.
If I can't see a clear pattern in the reports and figure out a way to reproduce them, I will probably just turn them off, as I'm confident the website still works as intended (in my environment/browser at least).

Add User-Agent to CSP reports

---

DragaliaAPI/version.json
PhotonStateManager/version.json

Makes it so Dependabot NuGet upgrades actually bump the nerdbank version

Include package versions in Nerdbank version calculation

---

Website/src/hooks.server.ts

Don't inject the mode watcher script for webview pages, otherwise users who have set a preference on the main website will see dark mode pages in-game, which contrasts with the light mode theme of the other game UI elements.
This only seems to happen on iOS, possibly because the browser local storage is shared between web-view and the system browser?

Force light mode for webview pages

---

DragaliaAPI/DragaliaAPI/Infrastructure/Middleware/ResultCodeLoggingMiddleware.cs

This code is returned when you enter an invalid ID, it isn't an actual error

Don't log error for FriendTargetNone result

---

DragaliaAPI/DragaliaAPI.Integration.Test/Features/Friends/FriendTest.cs
DragaliaAPI/DragaliaAPI/Features/Friends/FriendController.cs
DragaliaAPI/DragaliaAPI/Features/Friends/FriendService.cs
DragaliaAPI/DragaliaAPI/Infrastructure/Results/ResultCode.cs

Enforce the limit to friends, which ranges between 25 and 175 depending on player level.
Some complexity around requests - we want to check 'potential' friends as well, i.e. incoming and outgoing requests, so that it isn't possible to exceed the limit by having many requests accepted at once. The game has a handful of status codes to communicate this for both sides of the interaction.

Enforce friend limit

---

DragaliaAPI/DragaliaAPI.MissionDesigner/Missions/MemoryEvent/ACrescendoOfCourage.cs
DragaliaAPI/DragaliaAPI.MissionDesigner/Missions/MemoryEvent/ADashOfDisaster.cs
DragaliaAPI/DragaliaAPI.MissionDesigner/Missions/MemoryEvent/AWishToTheWinds.cs
DragaliaAPI/DragaliaAPI.MissionDesigner/Missions/MemoryEvent/AgentsOfTheGoddess.cs
DragaliaAPI/DragaliaAPI.MissionDesigner/Missions/MemoryEvent/ThePhantomsRansom.cs
DragaliaAPI/DragaliaAPI.Shared/Resources/Missions/MissionProgressionInfo.json

Adds the remaining event compendium endeavours for facility events.
I had a go at generating these using Gemini 2.5. I fed it some sample mission lists and some text files with data from the master asset. I had to fix about 5 missions out of ~125 in the end, but it was otherwise pretty much spot on. There could be some bugs I haven't seen, but from manual testing it looks to all function roughly correctly.

Add remaining facility event missions

---

DragaliaAPI/DragaliaAPI.MissionDesigner/Missions/MemoryEvent/AdventOfTheOrigin.cs
DragaliaAPI/DragaliaAPI.MissionDesigner/Missions/MemoryEvent/FaithForsakenPartOne.cs
DragaliaAPI/DragaliaAPI.MissionDesigner/Missions/MemoryEvent/FaithForsakenPartTwo.cs
DragaliaAPI/DragaliaAPI.MissionDesigner/Missions/MemoryEvent/ForgottenTruths.cs
DragaliaAPI/DragaliaAPI.MissionDesigner/Missions/MemoryEvent/FracturedFutures.cs
DragaliaAPI/DragaliaAPI.Shared/Resources/Missions/MissionProgressionInfo.json

Adds endeavours for the following compendium events:
- Advent of the Origin
- Faith Forsaken Part One
- Faith Forsaken Part Two
- Forgotten Truths
- Fractured Futures

Add compendium raid endeavours

---

DragaliaAPI/DragaliaAPI/Features/Web/Settings/SettingsController.cs
DragaliaAPI/DragaliaAPI/Features/Web/Settings/SettingsDto.cs
Website/src/routes/(main)/account/profile/+page.server.ts

When a switch is toggled off, it is absent from the form data. This leads to it being defaulted to true, meaning it is impossible to toggle off. Iterate a known set of setting keys so that our request object contains all of them with true/false values. Additionally introduce validation that all keys are in the request object with JsonRequired.

Fix disabling settings

---

DragaliaAPI/DragaliaAPI/Features/Shop/ShopService.cs

We incorrectly set shopPaymentType to Wyrmite in ShopService, which then fails a check later for payment mismatch. This results in the player being kicked to the title screen when they attempt to buy stamina with diamantium.

Fix error when refilling stamina with diamantium

---

DragaliaAPI/DragaliaAPI/Features/Summoning/SummonEffectHelper.cs
DragaliaAPI/DragaliaAPI/Features/Summoning/SummonService.cs

Summoning fake outs were broken in a refactor and can trigger on a summon without any 5* units, because the 'last 5* index' is incorrectly initialized to 0 instead of -1.
Additionally documentary evidence suggests that fake outs can only trigger when the unit is new

Fix summon fakeout

---

DragaliaAPI/DragaliaAPI/Resources/bannerConfig.json

In a local environment, no summon banners can be selected because they ran out in Feburary. This was fixed on the live server but not for the local environment.

Fix dev banner config

---

DragaliaAPI/DragaliaAPI.Integration.Test/Features/Login/SavefileImportTest.cs
DragaliaAPI/DragaliaAPI/Features/Login/Savefile/SavefileService.cs

Seeing some problems with save import after #1322 if you have an entry in the PlayerHelperUseDates table:
Because we configure restricted deletion on HelperUseDates, you can't delete a helper without first deleting the use dates, which we don't do on save import.
Fix this with an explicit delete on use dates.

Delete helper use dates on import

---

Aspire/Dawnshard.AppHost/Program.cs
DragaliaAPI/DragaliaAPI/Features/Dungeon/Record/DungeonRecordHelperService.cs
DragaliaAPI/DragaliaAPI/Features/Friends/FriendController.cs
DragaliaAPI/DragaliaAPI/Features/Friends/FriendService.cs

We currently return an error for sending a friend request to an existing friend by catching an FK exception from the DB. This works, but yields two error logs each time it happens which leads to false alarm when looking at the logs.
We can instead return `FriendApplyExists` from `id_search` after a manual query to prevent this, but leave the FK check just in case this is bypassed somehow. Most other ways to send a friend request (e.g. from co-op after a quest) should also block this using `ApplySendStatus`. This was not being done correctly which is also fixed in this PR.

Eagerly prevent sending duplicate friend requests

---

DragaliaAPI/DragaliaAPI.Integration.Test/Features/Present/PresentTest.cs
DragaliaAPI/DragaliaAPI/Features/Shared/Reward/Handlers/WeaponBodyHandler.cs

You can encounter a change tracker conflict error if you add the same weapon twice in the save editor because we don't check against the local view. Fix this scenario to report the second weapon as discarded instead.

Handle receiving duplicate weapon bodies

---

.husky/task-runner.json
DragaliaAPI/DragaliaAPI/Features/Friends/HelperService.cs
DragaliaAPI/DragaliaAPI/Features/Web/FeatureExtensions.cs
DragaliaAPI/DragaliaAPI/Infrastructure/Middleware/ResultCodeLoggingMiddleware.cs

- Add log of viewer ID to diagnose exceptions when looking up helpers
- Enable PII logging to debug `/api/user/me` request validation
Bonus:
- Don't log errors for friend request validation
- Also, csharpier fix following on from https://github.com/SapiensAnatis/Dawnshard/pull/1333 which upgraded to v2

Add logging to diagnose server errors

---

Website/src/hooks.server.ts

Every so often in the website logs we get:
```
Error: Unexpected /user/me response in OAuth callback: 401
```
Looking at the same time period in the API logs there will be a token validation failure like 
```
System.ArgumentException: IDX14309: Unable to decode the initialization vector as Base64Url encoded string.
---> System.FormatException: IDX10400: Unable to decode: '<redacted token bytes>, Bearer <redacted token bytes>' as Base64url encoded string.
```
I suspect this could be caused by having two `Authorization` headers based off of the `, Bearer` component (and maybe Identity is truncating them both?
I was able to reproduce this error on the production website by logging in, and then manually browing to `/login` and logging in again, in which scenario I have a cookie to add to the …

Avoid adding duplicate Authorization headers

---

DragaliaAPI/DragaliaAPI.Integration.Test/Features/Friends/SupportCharaTest.cs
DragaliaAPI/DragaliaAPI/Features/Friends/StaticHelperDataService.cs

When playing co-op, if you view details for another player, the client will make a call to /friend/get_support_chara_detail with their ID. If you have static helpers enabled, this will fail. We should fall back to real helper data to handle this case.
We expect this particular case to always hit this path rather than a static helper shadowing a real player, because all the static helper IDs are near ulong.MaxValue. So there is a clear separation, unless we get a LOT of new players.
Note: it shouldn't be necessary to do this for GetHelper above as that is only called from /friend/id_search.

Fix co-op error when using static helpers

---

Website/vite.config.ts

#1360 upgraded to Vite v7 which changes the baseline target from `modules` to `baseline-widely-available`, this was causing the Docker build to fail.

Fix website build
